### ISSUE TITLE
Compatibility with nginx-helper

### ISSUE THREAD

**Issue by michaeledi** [SatelliteWP/rocket-nginx#107]
Hi, I want to know if this plugin can be used with nginx-helper, which also handles the nginx fastcgi cache, will they be conflicting? Should I only use one of them? Thanks!

**Comment by maximejobin** [comment]
If you are using WP Rocket, I do believe you should use Rocket-Nginx and NOT nginx-helper.

If you are not using WP Rocket, using Rocket-Nginx is useless.
