### ISSUE TITLE
Alter media_header to medias_header

### ISSUE THREAD

**Issue by jotapepinheiro** [SatelliteWP/rocket-nginx#109]
Alter media_header in rocket-nginx.ini to medias_header

**Comment by maximejobin** [comment]
Thank you!

**Comment by Dibbyo456** [comment]
Ah, now I know why `media_header` was not working.

**Comment by maximejobin** [comment]
medias_extension or media_extensions needs standardization too.

**Comment by jstoeffler** [comment]
Just came here to say that there is still an inconsistency: the field is `medias_header` but apparently [media doesn't take an s](https://english.stackexchange.com/questions/314099/should-i-use-media-or-medias).

Also in the comments of the rocket-nginx.ini file it say:

    ; In the following example, the 'default' configuration is used and added a custom media_header.
    ;[example.com : default]
    ;media_header[Is-NewSection] = "Yes"

Which doesn't work.

**Comment by maximejobin** [comment]
Removed in version 3.0. So it is fixed.
