### ISSUE TITLE
SuperCache static files never being picked up despite try_files directive

### ISSUE THREAD

**Issue by pkiula** [SatelliteWP/rocket-nginx#110]
**Describe the bug**
Despite the right `try_files` directive, I can never see the supercached static file being picked up. I'd like to use supercache to make the site almost static-file based. Before invoking the Supercache's check of a cached file via PHP. 

**Versions**
Nginx: 1.16.1
WPSuperCache: latest
Nginx is the web server, with FastCGI and PHP-FPM 

**To Reproduce**
I try the curl command for my pages. The supercache plugin version is coming up, but no cache header. Not sure how to test that supercache is in fact serving these files as static? 

**Expected behavior**
Expected the curl command to show me the header. I manually changed a supercache file in the supercache path (`.../index-https.html`) and reloaded nginx, then curl again. Old file still showed. Perhaps supercache is picking up the gzip version of the file (`.../index-https.html.gz`), which I cannot manually change. How should I check if Nginx is in fact picking up the static file  from the supercache path? 

**Additional context**
This are my lines from my nginx.conf: 

        
     #  -- Supercache static ...
     #  https://github.com/pothi/wordpress-nginx/blob/master/globals/wp-super-cache.conf
     set $cachefile   /myadmin/wp-content/cache/supercache/${http_host}${request_uri}index-https.html;
     set $cachefile2  /wp-content/cache/supercache/${http_host}${request_uri}index-https.html;
        
     # Add cache file debug info as header
     add_header X-Cache-File $cachefile;
        
     try_files   $cachefile  $cachefile2  $uri  $uri/   /index.php$is_args$args ; 
        

Note that `myadmin` is sometimes the folder within which wp-admin is installed. So just to be safe I'm adding both URL constructs to Nginx.

**Comment by pkiula** [comment]
Just to add what curl shows: 

$ curl -I https://EXAMPLEDOMAIN.com/a-sample-url
    HTTP/2 200 
    date: Mon, 19 Aug 2019 15:30:03 GMT
    content-type: text/html; charset=UTF-8
    vary: Accept-Encoding
    vary: Accept-Encoding, Cookie
    cache-control: max-age=86400
    expires: Tue, 20 Aug 2019 15:30:03 GMT
    x-frame-options: SAMEORIGIN
    x-content-type-options: nosniff
    x-xss-protection: 1; mode=block
    referrer-policy: origin-when-cross-origin
    strict-transport-security: max-age=63072000; includeSubdomains
    x-cache: MISS
    
$ curl -I https://EXAMPLEDOMAIN.com/myadmin/wp-content/cache/supercache/EXAMPLEDOMAIN.com/a-sample-url/index-https.html
    HTTP/2 200 
    date: Mon, 19 Aug 2019 15:30:06 GMT
    content-type: text/html
    content-length: 27380
    last-modified: Mon, 19 Aug 2019 15:28:57 GMT
    vary: Accept-Encoding
    etag: "5d5ac039-6af4"
    expires: Wed, 21 Aug 2019 15:30:06 GMT
    cache-control: max-age=172800
    accept-ranges: bytes

**Comment by maximejobin** [comment]
This Rocket-Nginx configuration is made for being used with WP Rocket... not WP Super cache. This is why it's not working.

Also, based on your headers, it seems like Rocket-Nginx is not included correctly. Even if it was, it wouldn't work because it's only compatible with WP Rocket.
