### ISSUE TITLE
When I enable this, I get several issues. My wp control panel is a mess and get 520 on Cloudflare

### ISSUE THREAD

**Issue by Eckybrazzz** [SatelliteWP/rocket-nginx#111]
**Describe the bug**
520 error on Cloudflare and messed up wp control panel. These issues don't always appear. And are very difficult to troubleshoot. I already ditched an old server because I thought I had broken something that I could not fix again.

Last reply Cloudflare support 

> Your best bet is to work with your Hosting Provider or a WordPress expert to troubleshoot this.
A 520 error happens when your origin returns a response that is unexpected.
There are two key instances where this can happen in my experience:
1.	Your web server or networking equipment (Firewall, Load Balancer) reset the TCP connection after it was established. Sometimes when a web server crashes it will reset the connection. Check your web server error log for the timescale that the error occurred in and look for any error messages.
2.	Your web server returned an invalid response that exceeded our limits. Often this can happen if your web server is returning too many/too large headers. This is often caused by runaway scripts that return too many cookies, for example. The Code Igniter PHP framework has some known bugs around this too.

**Versions**
What version of Nginx are you using ? 1.17.3
What version of Rocket-Nginx are you using ? 2.2.1
What version of WP Rocket are you using ? 3.3.6
Are you using Nginx as a reverse proxy (with Apache for instance) ?No

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '.site or control panel'
2. Click on 'something or use other browsers'
4. See error 520 and a messed up control panel

Did you activate the debug in Rocket-Nginx ? yes on many domains
**example of headers:**
```
HTTP/1.1 200 OK
Date: Tue, 03 Sep 2019 09:45:50 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d6870d46b573331a397e55e1493ec3af01567503950; expires=Wed, 02-Sep-20 09:45:50 GMT; path=/; domain=.domain.com; HttpOnly; Secure
Last-Modified: Mon, 02 Sep 2019 22:19:09 GMT
Vary: Accept-Encoding
X-Powered-By: centminmod
Vary: Accept-Encoding, Cookie
Cache-Control: no-cache, no-store, must-revalidate
X-Rocket-Nginx-Serving-Static: Yes
X-Rocket-Nginx-Reason: /wp-content/cache/wp-rocket/x.domain.com///index-https.html_gzip
X-Rocket-Nginx-File: /home/nginx/domains/domain.com/public/wp-content/cache/wp-rocket/x.domain.com///index-https.html_gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: ie=edge
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-UA-Compatible: ie=edge
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5106XXXXXXa967d919-XXXX
```

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.

If needed will post them on paste.ee There are so many of them with centminmod and some differ a lot due to the fact I use different configs for several domains,

**Expected behavior**
A clean and workable wp admin page and no 520 errors 👍

**Comment by maximejobin** [comment]
Can you show how you include the Rocket-Nginx conf file in your main configuration ? Also, can you include the conf file you are using from Rocket-Nginx ?

**Comment by Eckybrazzz** [comment]
Guess I fixed most of the issues with some exclude rules in wp-rocket. The 520 error of Cloudflare I still have them, but also on domains where I don't use rocket-nginx. So have to figer out why I get these 520. It's not related anymore as I thought before to rocket-nginx.
