### ISSUE TITLE
What about the new WebP support in wp-rocket 3.4

### ISSUE THREAD

**Issue by Eckybrazzz** [SatelliteWP/rocket-nginx#113]
**Describe the bug**
What should we do to enable WebP caching now

**Versions**
What version of Nginx are you using ? 1.17.4
What version of Rocket-Nginx are you using ? latest
What version of WP Rocket are you using ? 3.4
Are you using Nginx as a reverse proxy (with Apache for instance) ?no

**Comment by JanThiel** [comment]
Pull Request ist prepared but still under discussion: https://github.com/SatelliteWP/rocket-nginx/pull/116
