### ISSUE TITLE
nginx 404 when using nginx server and not nginx-apache

### ISSUE THREAD

**Issue by tannerchung** [SatelliteWP/rocket-nginx#114]
**Describe the bug**
I found out that if I have  rocket-nginx enabled and am using a nginx server, all 404 pages will go to a nginx 404 page

I also found out that if I changed the login URL for WordPress with nginx-rocket enabled on an nginx server, that it will go to 404

using an nginx-apache server, 404 pages will hit the expected wordpress 404 page

**Versions**
What version of Nginx are you using ? 1.17.4-1+ubuntu18.04+1
What version of Rocket-Nginx are you using ? latest
What version of WP Rocket are you using ? 3.3.6
Are you using Nginx as a reverse proxy (with Apache for instance) ? Nginx reverse proxy with apache works fine, nginx by itself causes the error above

**To Reproduce**
Steps to reproduce the behaviour:
1. Change server from Nginx->Apache to Nginx
2. All nonexistent pages will go to the nginx 404 page

Did you activate the debug in Rocket-Nginx ? Please do and include any headers.

Not applicable

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.

I'm using the default nginx conf

**Expected behavior**

404 pages with an nginx server shouldn't be going to nginx 404 page

**Additional context**

**Comment by maximejobin** [comment]
Sorry for the delay. I never saw that issue before.

If Rocket-Nginx doesn't find your file on disk, it is falling back to the default behaviour. Are you having the issue when Rocket-Nginx is not included?
