### ISSUE TITLE
Query string cache

### ISSUE THREAD

**Issue by asolari** [SatelliteWP/rocket-nginx#115]
I enabled in WP-Rocket the query string cache for a few keywords, which would benefit from caching.

As an example:, the following request:     `/dir1/dir2/?age[]=4-12-years`

is saved by WP-Rocket to:     `/wp-content/cache/wp-rocket/my-site.com/dir1/dir2/_age%5b0%5d=4-12-years/`

How should I configure rocket-nginx to search for the corresponding cached files?
Is it possibile?

Thank you.

**Comment by JanThiel** [comment]
rocket-nginx currently does not support Query Parameter caching. See the nginx config file:
```
# Do not bypass if arguments are found (e.g. ?page=2)
if ($is_args) {
	set $rocket_bypass 0;
	set $rocket_reason "Arguments found";
}
```

**Comment by maximejobin** [comment]
This is a feature I've been working on in the DEV branch. Not ready to be released, yet.

**Comment by dillix** [comment]
@maximejobin is there any news? We need this to serve big feeds.

**Comment by maximejobin** [comment]
@dillix No ETA for now. All made by volunteer work, this is unfortunately not a priority unless someone sponsors it. I'm sorry I can't do more.

**Comment by dillix** [comment]
@maximejobin how much this work could be cost?

**Comment by maximejobin** [comment]
Sorry if you thought I was talking about money. I was talking about giving time to code what is missing. That's the kind of sponsorship this project is looking for.

If you would like to pay for it, that would be great. I guess it is roughly a 20 hours of time to do and test such feature.

You can contact SatelliteWP directly for that and we will gladly implement it and list your company as a sponsor of the project :
https://www.satellitewp.com/en/contact/

**Comment by maximejobin** [comment]
@dillix If you want to support the project, I encourage you to sponsor it via this link:
https://github.com/sponsors/SatelliteWP

**Comment by benfavre** [comment]
I ended up going for a varnish setup infront of wp-rocket.
Seems overkill but it has other benefits.

**Comment by maximejobin** [comment]
This was added to version 3.0.
