### ISSUE TITLE
Running Rocket-Nginx with Plesk

### ISSUE THREAD

**Issue by TaktlosDE** [SatelliteWP/rocket-nginx#117]
**Describe the bug**
There is no header set to Cache the files in the browser.

**Versions**
What version of Nginx are you using ?
1.16.1

What version of Rocket-Nginx are you using ?
Up to Date

What version of WP Rocket are you using ?
FULL NGINX and up to date

**To Reproduce**
Do a curl -IL on lapiazza-verden.de

Did you activate the debug in Rocket-Nginx ? Please do and include any headers.
It is active you can check

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.
Only rocket nginx

**Expected behavior**
I want the images css js cached for 30 Days from Rocket Nginx

**Comment by TaktlosDE** [comment]
PS: I am using Plesk as you can see in the Headers

**Comment by andreutesch** [comment]
i have the exact same problem with our setup / server for any page

Versions:
dedicated server + plesk Version 18.0.20
nginx version: nginx/1.16.1
latest version of wp-rocket
latest version of rocket-nginx
Redis version=5.0.6
Redis Object Cache + PhpRedis (v5.1.0)

Works for HTML Files (buggy on frontpage only with mobile cache activated)
x-rocket-nginx-file | /var/www/vhosts/shirtgeschwist…de//contact//index-https.html
-- | --
x-rocket-nginx-reason | /wp-content/cache/wp-rocket/sh…de//contact//index-https.html
x-rocket-nginx-serving-static | Yes

But not working for any other static content such as css png js etc.


x-rocket-nginx-file | /var/www/vhosts/shirtgeschwist…-300x300.png/index-https.html
-- | --
x-rocket-nginx-reason | File not cached
x-rocket-nginx-serving-static | No

site:

https://shirtgeschwister.de

regards

**Comment by maximejobin** [comment]
I don't have a Plesk environment. Therefore, I don't have an answer to configure it properly. I do believe it is not Rocket-Nginx the problem. It is probably the link between Plesk and Rocket-Nginx.

This would be paid work if you want to contact SatelliteWP : 
https://www.satellitewp.com/en/contact/

Thank you for your understanding.

**Comment by lewebsimple** [comment]
I'm also having troubles configuring this on Plesk 18.0.24.
It works fine for logged-out users, but I can't see the admin bar once logged-in.
I will report back once I get it to work.

**Comment by lewebsimple** [comment]
I got it to work by enabling every option in Apache & nginx Settings > nginx settings in Plesk (proxy mode / smart static file processing / serve static files directly by nginx / enable nginx caching) and adding `include /etc/nginx/rocket-nginx/default.conf;` in additional nginx directives.
I also enabled user cache in WP-Rocket settings.

**Comment by andreutesch** [comment]
did u check if u really serve static html files that way with debug enabled in the rocket nginx cfg - and checked the response headers?

**Comment by lewebsimple** [comment]
@andreutesch Yup the response header was there in debug mode, indicating the static cache was served by NGINX.

Of course this was only the case when logged out.

**Comment by maximejobin** [comment]
@lewebsimple is everything working as it should now?

**Comment by skmezanul** [comment]
> I got it to work by enabling every option in Apache & nginx Settings > nginx settings in Plesk (proxy mode / smart static file processing / serve static files directly by nginx / enable nginx caching) and adding `include /etc/nginx/rocket-nginx/default.conf;` in additional nginx directives.
> I also enabled user cache in WP-Rocket settings.

If you enable Proxy mode, you are basically using Apache to serve the website and nginx will only act as a proxy server (default way of how Plesk serves any website). In the default mode, you don't even need to run Rocket-Nginx as WP Rocket will work fine. Also, you should not enable nginx cache from Apache & nginx Settings as it will cause issues unless you manually exclude cookies, etc and set it up properly. If your site is a simple WordPress site, you may not see any issues though.

If you want to use only PHP-FPM and nginx, you shouldn't enable Proxy mode. Please note in this mode, the .htaccess files will not be recognized and your permalinks will stop working. You then have to configure Plesk according to the instructions given here: https://support.plesk.com/hc/en-us/articles/213912945--After-switching-a-WordPress-website-to-FPM-served-by-nginx-in-Plesk-it-fails-to-load-with-404-Not-Found-on-all-pages-except-start-page

**Comment by moazam1** [comment]
@maximejobin I am confused how this setup works? I am using plesk but it's less important what control panel I am using. I noticed you are not using try_files. So how come it's gonna match uri and serve file from cache? Below is my generated nginx conf file:

```
###################################################################################################
# Rocket-Nginx
#
# Rocket-Nginx is a NGINX configuration to speedup your WordPress
# website with the cache plugin WP-Rocket (http://wp-rocket.me)
#
# Author: Maxime Jobin
# URL: https://github.com/maximejobin/rocket-nginx
#
# Tested with WP-Rocket version: 3.6.0.1
# Tested with NGINX: 1.19 (mainline)
#
# Version 2.1.1
#
###################################################################################################

# Add debug information into header
set $rocket_debug 0;


###################################################################################################
# Do not alter theses values
#
set $rocket_bypass 1;				# Should NGINX bypass WordPress and call cache file directly ?
set $rocket_encryption "";			# Is GZIP accepted by client ?
set $rocket_file "";				# Filename to use
set $rocket_is_bypassed "No";		# Header text added to check if the bypass worked or not. Header: X-Rocket-Nginx-Serving-Static
set $rocket_reason "";				# Reason why cache file was not used. If cache file is used, what file was used
set $rocket_https_prefix "";		# HTTPS prefix to use when cached files are using HTTPS
set $rocket_hsts 0;					# Is HSTS is off (0) by default. Will be turned on (1) if request is HTTPS

# HSTS value
set $rocket_hsts_value "max-age=31536000; includeSubDomains";

###################################################################################################
# PAGE CACHE
#

# Is GZIP accepted by client ?
if ($http_accept_encoding ~ gzip) {
	set $rocket_encryption "_gzip";
}

# Is Brotli accepted by client ?
if ($http_accept_encoding ~ br) {
	set $rocket_encryption "";
}

# Is SSL request ?
if ($https = "on") {
	set $rocket_https_prefix "-https";
	set $rocket_hsts 1;
}

# If HSTS is disabled, unset HSTS set for Rocket-Nginx configuration
if ($rocket_hsts = "0") {
	set $rocket_hsts_value "";
}

# File/URL to return IF we must bypass WordPress
# Desktop: index.html or index-https.html
# Mobile:  index-mobile.html or index-mobile-https.html
set $rocket_end "/cache/wp-rocket/$http_host/$request_uri/index$rocket_https_prefix.html$rocket_encryption";
set $rocket_url "/wp-content$rocket_end";
set $rocket_file "$document_root/wp-content$rocket_end";
set $rocket_mobile_detection "$document_root/wp-content/cache/wp-rocket/$http_host/$request_uri/.mobile-active";


# Do not bypass if it's a POST request
if ($request_method = POST) {
	set $rocket_bypass 0;
	set $rocket_reason "POST request";
}

# Do not bypass if arguments are found (e.g. ?page=2)
if ($is_args) {
	set $rocket_bypass 0;
	set $rocket_reason "Arguments found";
}

# Do not bypass if the site is in maintenance mode
if (-f "$document_root/.maintenance") {
	set $rocket_bypass 0;
	set $rocket_reason "Maintenance mode";
}

# Do not bypass if one of those cookie if found
# wordpress_logged_in_[hash] : When a user is logged in, this cookie is created (we'd rather let WP-Rocket handle that)
# wp-postpass_[hash] : When a protected post requires a password, this cookie is created.
if ($http_cookie ~* "(wordpress_logged_in_|wp\-postpass_|woocommerce_items_in_cart|woocommerce_cart_hash|wptouch_switch_toogle|comment_author_|comment_author_email_)") {
	set $rocket_bypass 0;
	set $rocket_reason "Cookie";
}

if (-f "$rocket_mobile_detection") {
	set $rocket_bypass 0;
	set $rocket_reason "Specific mobile cache activated";
}

# Do not bypass if the cached file does not exist
if (!-f "$rocket_file") {
	set $rocket_bypass 0;
	set $rocket_reason "File not cached";
}

# If the bypass token is still on, let's bypass WordPress with the cached URL
if ($rocket_bypass = 1) {
	set $rocket_is_bypassed "Yes";
	set $rocket_reason "$rocket_url";
}

# Clear variables if debug is not needed
if ($rocket_debug = 0) {
	set $rocket_reason "";
	set $rocket_file "";
}

# If the bypass token is still on, rewrite according to the file linked to the request
if ($rocket_bypass = 1) {
	rewrite .* "$rocket_url" last;
}

# Add header to HTML cached files
location ~ /wp-content/cache/wp-rocket/.*html$ {
	etag on;
	add_header Vary "Accept-Encoding, Cookie";
	add_header Cache-Control "no-cache, no-store, must-revalidate";
	add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
	add_header X-Rocket-Nginx-Reason $rocket_reason;
	add_header X-Rocket-Nginx-File $rocket_file;
	add_header Strict-Transport-Security "$rocket_hsts_value";
}

# Do not gzip cached files that are already gzipped
location ~ /wp-content/cache/wp-rocket/.*_gzip$ {
	etag on;
	gzip off;
	types {}
	default_type text/html;
	add_header Content-Encoding gzip;
	add_header Vary "Accept-Encoding, Cookie";
	add_header Cache-Control "no-cache, no-store, must-revalidate";
	add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
	add_header X-Rocket-Nginx-Reason $rocket_reason;
	add_header X-Rocket-Nginx-File $rocket_file;
	add_header Strict-Transport-Security "$rocket_hsts_value";
}

# Debug header (when file is not cached)
add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
add_header X-Rocket-Nginx-Reason $rocket_reason;
add_header X-Rocket-Nginx-File $rocket_file;

# No HSTS header added here. We suppose it's correctly added in the site configuration


###################################################################################################
# BROWSER CSS CACHE
#
location ~* \.css$ {
	etag on;
	gzip_vary on;
	expires 30d;

}


###################################################################################################
# BROWSER JS CACHE
#
location ~* \.js$ {
	etag on;
	gzip_vary on;
	expires 30d;

}


###################################################################################################
# BROWSER MEDIA CACHE
#
location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg)$ {
	etag on;
	expires 30d;

}
```

**Comment by cbstudiomx** [comment]
I`m getting the same issue, rocket nginx does not create caches files because of:

[root@xxx nginx]# git clone https://github.com/satellitewp/rocket-nginx.git
Cloning into 'rocket-nginx'...
remote: Enumerating objects: 379, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 379 (delta 37), reused 51 (delta 32), pack-reused 318
Receiving objects: 100% (379/379), 86.96 KiB | 3.48 MiB/s, done.
Resolving deltas: 100% (200/200), done.
[root@xxx nginx]# cd rocket-nginx
[root@xxx rocket-nginx]# cp rocket-nginx.ini.disabled rocket-nginx.ini
[root@xxx rocket-nginx]# php rocket-parser.php
-bash: php: command not found

Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete. 

Please help!

**Comment by maximejobin** [comment]
> Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete.

I truly doubt you cannot run PHP as root. That being said, with multiple versions of PHP installed, maybe you have to add the version to the command. Please contact your host so they can assist you. This has nothing to do with Rocket-Nginx.

**Comment by szuperman** [comment]
Guy, have anybody solution for "php rocket-parser.php"?
/etc/nginx/rocket-nginx# php rocket-parser.php
-bash: php: command not found

I never heard run anything with "php" command. (I have Plesk)

**Comment by vaccinemedia** [comment]
> > Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete.
> 
> I truly doubt you cannot run PHP as root. That being said, with multiple versions of PHP installed, maybe you have to add the version to the command. Please contact your host so they can assist you. This has nothing to do with Rocket-Nginx.

New servers with Plesk installed do not come with PHP cli installed - only the php-fpm which you need. So on a fresh server with Plesk you have to install php in order to use it via the command line.

**Comment by vaccinemedia** [comment]
@szuperman did you ever get it working? I'm struggling to find any documentation or tutorials on how to get NGinx proxy serving the cached files properly and so every request to the server is currently running a php instance and my server response time has tanked. If you can let me know if you got it working on Plesk with apache and Nginx proxy that would be awesome :)

**Comment by exl1ps3** [comment]
> I`m getting the same issue, rocket nginx does not create caches files because of:
> 
> [root@xxx nginx]# git clone https://github.com/satellitewp/rocket-nginx.git Cloning into 'rocket-nginx'... remote: Enumerating objects: 379, done. remote: Counting objects: 100% (61/61), done. remote: Compressing objects: 100% (28/28), done. remote: Total 379 (delta 37), reused 51 (delta 32), pack-reused 318 Receiving objects: 100% (379/379), 86.96 KiB | 3.48 MiB/s, done. Resolving deltas: 100% (200/200), done. [root@xxx nginx]# cd rocket-nginx [root@xxx rocket-nginx]# cp rocket-nginx.ini.disabled rocket-nginx.ini [root@xxx rocket-nginx]# php rocket-parser.php -bash: php: command not found
> 
> Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete.
> 
> Please help!

For Plesk, you can try the following command:
/opt/plesk/php/8.0/bin/php rocket-parser.php
The value 8.0 is the installed Plesk version. You may have 7.4.

**Comment by wurkagency** [comment]
> > Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete.
> 
> I truly doubt you cannot run PHP as root. That being said, with multiple versions of PHP installed, maybe you have to add the version to the command. Please contact your host so they can assist you. This has nothing to do with Rocket-Nginx.

php cannot be run as root and especially not in plesk, where it's jailed.

**Comment by vaccinemedia** [comment]
> > > Like you see, we, users of Pesk, if we access server like root, we can not run command php like root so your script does not create the default config, so the install its incomplete.
> > 
> > 
> > I truly doubt you cannot run PHP as root. That being said, with multiple versions of PHP installed, maybe you have to add the version to the command. Please contact your host so they can assist you. This has nothing to do with Rocket-Nginx.
> 
> php cannot be run as root and especially not in plesk, where it's jailed.

PHP can be installed and run as root. That's what the root user is for - it can do anything on the system without restrictions.
![Screenshot-2023-10-11-at-09 16 12](https://github.com/SatelliteWP/rocket-nginx/assets/10465885/0562a023-27d4-4c6d-bc45-180a0484acb0)

What I need to know is how I can use the generated config. Do I need to copy and paste it into the additional NGinx directives in the Apache / NGinx settings for the website? Or is there a way of referencing it instead?

**Comment by vaccinemedia** [comment]
OK what I did was follow the instructions to clone the git repo, entered the rocket-nginx folder and ran the php file to create the config then I have the following in my additional NGinx directives:
# Rocket-Nginx configuration
include /etc/nginx/rocket-nginx/conf.d/default.conf;

Here is what I'm seeing in Chrome inspector with the debug enabled in the rocket-nginx config:

![Screenshot 2023-10-11 at 09 52 37](https://github.com/SatelliteWP/rocket-nginx/assets/10465885/3b4b226c-d825-4bba-96b9-dfe85868985e)

So it appears to be working!

**Comment by akkiverma** [comment]
I tried this, but always getting MISS on serving-static, any solution for it?
