### ISSUE TITLE
Strange paths in nginx cache files making rocket-nginx not work

### ISSUE THREAD

**Issue by Gruncher** [SatelliteWP/rocket-nginx#118]
I've been playing with this plugin for a few hours and this is the point I'm at:

The front page of my site does work properly, showing "x-rocket-nginx-serving-static: Yes"

However, every other page does not work properly, and here is an example:

x-rocket-nginx-file: /var/www/abc/wp-content/cache/wp-rocket/www.websitecom//category/morepath//index-https.html
x-rocket-nginx-reason: File not cached

However, if I look at the server itself, the file IS cached, but it's in a strange folder:

/var/www/abc/wp-content/cache/wp-rocket/www.websitecom//category/morepath/#q=%2fcategory%2fmorepath%2f#/index-https.html

Any idea why this would be?

**Comment by maximejobin** [comment]
Hello, it is probably because you activated query strings but they are not supported by Rocket-Nginx... yet.

**Comment by duncanplatt** [comment]
Hello Maxime!

I am running into the same issue:

x-rocket-nginx-file | /home/goodnews/webapps/Domain/cache/cache/wp-rocket/www.domain.org//i_am_not_ashamed//index-https.html

The double slashes make the file undiscoverable.

**Comment by maximejobin** [comment]
Can you confirm that running this command line:

    cat /home/goodnews/webapps/Domain/cache/cache/wp-rocket/www.domain.org//i_am_not_ashamed//index-https.html

... produces a different result than running this:

    cat /home/goodnews/webapps/Domain/cache/cache/wp-rocket/www.domain.org/i_am_not_ashamed//index-https.html

**Comment by shaneonabike** [comment]
I can confirm that using cat works with there are double slashes or single. I'm going to log a different issues for my problem.
