### ISSUE TITLE
It module prefer load non-webp html if it exists !

### ISSUE THREAD

**Issue by thanh25896** [SatelliteWP/rocket-nginx#120]
**Describe the bug**
Enable webp cache then wp-rocket will create *.html and -webp.html so nginx rocket module prefer load *.html for jpeg images

**Versions**
What version of Nginx are you using ? 1.17.9
What version of Rocket-Nginx are you using ? Latest
What version of WP Rocket are you using ? 3.5.0.4
Are you using Nginx as a reverse proxy (with Apache for instance) ? No

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Meida tab'
2. Click on 'Enable Webp Cache'
3. Scroll down to 'Save'
4. wp-rocket will create  -webp.html and *.html  If surf the site with non support webp browser)
5. After that refresh the support webp browser but still serve the *.html

**Comment by maximejobin** [comment]
webp is not working with all browsers. Nginx configuration scripting is not made to validate browsers and do "complex" logic... unfortunately.
