### ISSUE TITLE
Nginx + affiliatetheme.io => img -> index.php

### ISSUE THREAD

**Issue by drexlma** [SatelliteWP/rocket-nginx#122]
We have an URL: /at-get-img/2657/0/ravensburger-21424-spielhaus.jpg
It is not an real URL. It should relate do index.php

I dont no why.

For some reason, this config makes it not work. (Without content)
 
location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg)$ {
}

**Comment by maximejobin** [comment]
You can alter the extensions that are displayed from de configuration file.

**Comment by maximejobin** [comment]
If you want your code to work, you have to remove the `location` part totally. Not only remove what is inside.
