### ISSUE TITLE
Nginx With Centminmod

### ISSUE THREAD

**Issue by gutitti** [SatelliteWP/rocket-nginx#125]
header result :

    X-Rocket-Nginx-Serving-Static: No
    X-Rocket-Nginx-Reason: Specific mobile cache activated
    X-Rocket-Nginx-File: /home/nginx/domains/domain.com/public/wp-content/cache/wp-rocket/domain.com///index-https.html_gzip

I found 3 user in centminmod using rocket-nginx with no problem and 1 user with same problem.

i try using at location / {

    try_files $uri $uri/ /index.php?q=$uri&$args;

or

    try_files $uri $uri/ /index.php?$args;

or

    try_files "/wp-content/cache/wp-rocket/$host${uri}$is_args$args/index-https.html_gzip" $uri $uri/ /index.php$is_args$args;

But header result still X-Rocket-Nginx-Serving-Static: No

when i using cat /home/nginx/domains/domain.com/public/wp-content/cache/wp-rocket/domain.com///index-https.html file is lived and cached in folder /wp-content/cache/wp-rocket/

**Comment by gutitti** [comment]
Fixed  : only must disable mobile cache
But how will it support mobile seperate cache in future ? because my themes has mobile conditional when mobile detected will hide some feature ( example : sidebar and footer navigation )

**Comment by maximejobin** [comment]
As per the documentation:

> **Specific mobile cache activated**: If you activated specific cache (one for mobile and one for desktop) in WP-Rocket, HTML files (pages, posts, ...) won't be served directly because Rocket-Nginx cannot know if the request was made by mobile or desktop device.

You have to disable "Mobile caching" in WP Rocket.
