### ISSUE TITLE
x-rocket-nginx-reason: File not cached

### ISSUE THREAD

**Issue by DavidBabinec** [SatelliteWP/rocket-nginx#126]
Hello,

I am currently using Gridpane with Vultr and installed rocket nginx. I enabled debug but I am still seeing:

x-rocket-nginx-reason: File not cached

Although the website obviously serves cached version in some way and it also seems that the file path in x-rocket-nginx-file seems to be correct. It also shows 

cache-control: public, max-age=31535990, stale-while-revalidate=10, stale-if-error=10

but also:

x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No

It seems that it serves cached file but not via this  configuration. I have wp rocket enabled (separate mobile cache is disabled), cloudflare for DNS only and Redis and Fastcgi is disabled.

Can you please help me? What can be wrong?

Thank you very much!

**Comment by maximejobin** [comment]
If you get "File not cached", it means Rocket-Nginx could not find it on disk. Therefore, it cannot serve it.
