### ISSUE TITLE
Security header in rocket-nginx.ini

### ISSUE THREAD

**Issue by cheonmux** [SatelliteWP/rocket-nginx#127]
Hi, 

I want to put add_header code like below in rocket-nginx.conf.

`add_header x-xss-protection "1; mode=block" always;
add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;`

I read #89  but i dont understand how do i put code in rocket-nginx.ini before rocket-parser.

I tested to put that codes end of rocket-nginx.ini or put in default.conf directly. but syntax error occur and not working.

Please let me know how do i put 

Thank you.

**Comment by virgilio27** [comment]
In rocket-nginx.ini, section HTTP(S) headers:

`http_header[X-Frame-Options] = "SAMEORIGIN";
http_header[X-Content-Type-Options] = "nosniff";
http_header[X-XSS-Protection] = "1; mode=block";
http_header[Referrer-Policy] = "no-referrer-when-downgrade";
http_header[Expect-CT] = "enforce; max-age=3600";`

**Comment by maximejobin** [comment]
This is the right way for now. I'm working on a new version where you will be able to include another file in your configuration.
