### ISSUE TITLE
Why set cache-control to "no-cache"?

### ISSUE THREAD

**Issue by blogtutor** [SatelliteWP/rocket-nginx#128]
We recently ran into an issue for a site that is using your nginx setup for WP Rocket, and is also behind the Sucuri Firewall proxy service.  

The nginx configuration is setting the `Cache-control` header to `no-cache, no-store, must-revalidate`:

https://github.com/SatelliteWP/rocket-nginx/blob/25a3b6f3bd3504d65ac3920cd96612d74043f87f/rocket-nginx.ini.disabled#L21

We have Sucuri configured to [cache based on site headers](https://docs.sucuri.net/website-firewall/performance/caching-options/).  (We're not using Sucuri's default "Enabled" option since that can be a bit too aggressive...  )

So Sucuri is respecting the Cache-control header, and not caching the HTML document at their edge location.  But we definitely want Sucuri caching and distributing the HTML.

When WP Rocket configures .htaccess for Apache, [it only appends `public` to the Cache-Control header. ](https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/functions/htaccess.php#L549)

Why does the nginx config add `no-cache`, instead of matching what WP Rocket is doing by default?

Thanks!

**Comment by maximejobin** [comment]
After doing multiple tests, it was found that this way of doing things was the best way to not serve an old file from the Nginx cache if a newer version was available and force the browser to do at least a basic validation.

I read a lot about all the values and once I found this combination, all issues reported about serving the wrong file stopped. These values are what makes the configuration work with almost every site and reduces the support we must do.

That being said, you can change the configuration file to "public" if it better suits your needs.

**Comment by maximejobin** [comment]
As to "why" exactly I used `no-cache`, I suggest you take a look at this explanation:

https://www.keycdn.com/blog/http-cache-headers#public-vs-private

**Comment by blogtutor** [comment]
Thanks @maximejobin for the explanation!

So by adding the `no-cache` you're basically telling the browser it should never cache that document locally... so that slows things down for pages that _could_ be served from a local cache, and has the other the side effect (as I mentioned above) is that it can tell other proxies (like Sucuri) not to cache it, either.  But I can certainly see the appeal of this, from a content-consistency and support perspective.

I'm curious, did you test with the `max-age` and `must-revalidate` options used in conjunction?  I would guess that could be a better way to control browser caching, in order to strike a better balance?  That would still require the roundtrip to the server, but then if it's below the max-age limit, it would still be able to use the browser's (or proxy's) cache. 🤔

**Comment by maximejobin** [comment]
> I'm curious, did you test with the max-age and must-revalidate options used in conjunction?

I did not. My goal with this project is to provide a great configuration that covers as many cases as possible.

What you are suggesting makes a lot of sense in most cases, I think. For my own websites, I edit the configuration to make it even better according to the particular use-case I have. That being said, I also wanted someone with little to no technical expertise to simply include the script without understanding and get results.

> I would guess that could be a better way to control browser caching, in order to strike a better balance?

More than that, you probably don't have to revalidate at all if you cache the page for an hour or a day in most cases. That being said, make sure you don't make a mistake and ask revalidation in a year (or any crazy value according to your use-case). That is why I didn't want to include a value that could be too aggressive!

**Comment by blogtutor** [comment]
Agreed!  I think it would make sense for the `max-age` to match the cache timeout limit that's set in the WP Rocket settings (default is 10 hours).

I've been working with a hosting company that followed your guidelines and implements this on their end (and we don't have direct access to their nginx setup), so this is very helpful info. I'll bring this back to them and we can discuss how they might want to tweak their usual settings.  Thanks again!
