### ISSUE TITLE
Why Mobile cache no work?

### ISSUE THREAD

**Issue by virgilio27** [SatelliteWP/rocket-nginx#130]
When to access a mobile cache will be implemented?

**Comment by maximejobin** [comment]
Mobile cache cannot be implemented easily. Knowing if a device is a mobile or a tablet requires logic that cannot be implemented in the NGINX rules.

Isn't your theme responsive? Most themes are responsive and it is not needed to activate mobile cache.

**Comment by virgilio27** [comment]
But here is posible, look: [https://github.com/pothi/wordpress-nginx/blob/master/globals/wp-rocket.conf](url)

**Comment by virgilio27** [comment]
> Mobile cache cannot be implemented easily. Knowing if a device is a mobile or a tablet requires logic that cannot be implemented in the NGINX rules.
> 
> Isn't your theme responsive? Most themes are responsive and it is not needed to activate mobile cache.

But here is posible, look: [ https://github.com/pothi/wordpress-nginx/blob/master/globals/wp-rocket.conf](url)

`try_files "/wp-content/cache/wp-rocket/$host${uri}$is_args$args/index-mobile$https_suffix.html" $uri $uri/ /index.php$is_args$args;`

**Comment by maximejobin** [comment]
This code is incomplete. It simili-works.

I worked on integrating it in the past and stopped to avoid receiving issues about mobility not working.
