### ISSUE TITLE
How to add access_log off through rocket-nginx.ini?

### ISSUE THREAD

**Issue by virgilio27** [SatelliteWP/rocket-nginx#131]
Some way to add **access_log off** and **log_not_found off** for location media cache? 
I mean via rocket-nginx.ini.

```
location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg)$ {
	etag on;
	expires 30d;
	
}
```

**Comment by maximejobin** [comment]
This could be added in a next version as it is not possible for now.

**Comment by maximejobin** [comment]
This will be possible in version 3.0

**Comment by maximejobin** [comment]
This is now possible as you can include files with your own rules.
