### ISSUE TITLE
Question: Does this support Nginx in reverse proxy mode?

### ISSUE THREAD

**Issue by dciphered** [SatelliteWP/rocket-nginx#132]
Hi,

Just wanting to confirm if the script supports Nginx deployed as a reverse proxy to Apache? My deployment is running on Plesk with the latest version of all components including WpRocket.

Many thanks.

**Comment by maximejobin** [comment]
Many users are using it and it works!

The scripts serves a file directly only if it finds it. Otherwise, it does nothing.

I know other users have had some issues to make the Plesk configuration work correctly. It seems like once you figure it out, you're good to go.
