### ISSUE TITLE
Permission denied when cloning the repository

### ISSUE THREAD

**Issue by Venom7719** [SatelliteWP/rocket-nginx#133]
fatal: could not create work tree dir 'rocket-nginx': Permission denied

**Comment by maximejobin** [comment]
I do not know what you are doing... but it is not linked to Rocket-Nginx.

You probably don't have the rights to clone the project wherever you are cloning it.

**Comment by Venom7719** [comment]
I tried this
sudo chown -R ubuntu etc/nginx
but I get
chown: cannot access 'etc/nginx': No such file or directory

**Comment by maximejobin** [comment]
Changing the ownership of `/etc/nginx` is a really bad idea.

I would rather clone Rocket-Nginx as `root` : 

    sudo git clone ....
    chown -R root rocket-nginx
   ...

**Comment by maximejobin** [comment]
By the way, this is more about "how to be a sysadmin" and is not something we can support. Please make sure you know what you do as this can have consequences.
