### ISSUE TITLE
Can the rocket-nginx.tmpl file be edited to add our own rules? 

### ISSUE THREAD

**Issue by amityweb** [SatelliteWP/rocket-nginx#138]
Your documentation says to edit the ini file to add in our own configuration. I am not how I would go about adding in the webp code I want which is below. You make no mention of editing the rocket-nginx.tmpl file. Can we edit that file? 

I need to add this:
```
    add_header Vary Accept;
    if ($http_accept ~* "webp"){
        set $imwebp A;
    }
    if (-f $request_filename.webp) {
        set $imwebp  "${imwebp}B";
    }
    if ($imwebp = AB) {
        rewrite ^(.*) $1.webp;
    }
```

**Comment by maximejobin** [comment]
It is not recommended to change the template file.

Version 3.0 will manage WEBP.

**Comment by amityweb** [comment]
Great. But I need it now so have changed both files to add in webp.
