### ISSUE TITLE
Uninstall Method

### ISSUE THREAD

**Issue by artsmm** [SatelliteWP/rocket-nginx#139]
Hi!

Is there a way to uninstall Rocket-nginx gracefully?
I move my Wordpress to another server using a tool called Spinup WP.
The rocket-nginx directory isn't getting copied, so I get errors withing the moving tool (My config file does get moved and includes reference to the non existing directory). If I preinstall rocket-nginx on the destination server, migration works without errors. But then I do get other errors, so in order to minimize any side factors I want to uninstall rocket-nginx completely.
I, of course, tried to delete the reference from my site config & the rocket-nginx folder but I still got an error while moving my server. 

Is there anything I'm missing?
Thanks

**Comment by maximejobin** [comment]
> Is there a way to uninstall Rocket-nginx gracefully?

1. Remove every Rocket-Nginx "include" you have added in your Nginx configuration files.
2. Reload Nginx (usually with `service nginx reload`).
3. Delete Rocket-Nginx folder.
