### ISSUE TITLE
Cache file has a wrong name

### ISSUE THREAD

**Issue by LaurentLeLynx** [SatelliteWP/rocket-nginx#142]
Hello :)

We would like to set up our server cache via rocket-nginx. However we are encountering some difficulties.
We discovered that the targeted file has a wrong name ->

X-Rocket-Nginx-File : wp-content/cache/wp-rocket/xxxxxxxxx/index.html_gzip

But our file is named differently by Wp-Rocket --> index-https.html_gzip

How could we update this and solve this issue ?

Thank you very much for your help.

Laurent

**Comment by maximejobin** [comment]
If it is trying to serve the non-https file, it is because the received request is not using HTTPS.

The version 3 of Rocket-Nginx (not released yet) will manage forwarded requests. Until it is released, the call must use HTTPS to serve the `index-https.html_gzip` file.

**Comment by LaurentLeLynx** [comment]
Thank you Maxime for the quick answer.

When the version 3 will be released ? Is it a question of days, months ?

Thank you very much,


Laurent

**Comment by maximejobin** [comment]
I'm waiting for an answer from WP Rocket to finalize everything. In theory, only final testing (and adjustments!) needs to be done.

**Comment by maximejobin** [comment]
For your information, this is where we are waiting for an answer to release the next version:
https://github.com/wp-media/wp-rocket/issues/3207

**Comment by maximejobin** [comment]
Duplicate of #101
