### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by Zyles** [SatelliteWP/rocket-nginx#143]
**Describe the bug**

Followed the guide, installed and I refreshed page 5 times and all I get is:

`x-rocket-nginx-serving-static: No`

Nothing else.

**Versions**
What version of Nginx are you using ? nginx version: nginx/1.14.0 (Ubuntu)
What version of Rocket-Nginx are you using ? Latest
What version of WP Rocket are you using ? 3.7.5
Are you using Nginx as a reverse proxy (with Apache for instance) ? No

**To Reproduce**

1. Install WP & Woocommerce
2. Install WP Rocket
3. Install Rocket Nginx
4. ???

Did you activate the debug in Rocket-Nginx ? Please do and include any headers.

Yes
`x-rocket-nginx-serving-static: No`

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.

Used defaults

**Expected behavior**

Caching and headers described in readme

**Additional context**

Woocommerce
HTTPS

Nginx config:
```
server {
    listen 80;
    listen [::]:80;
    server_name *.example.com example.com;
    rewrite ^ https://$host$request_uri permanent;
}

server {
    # Rocket-Nginx configuration
    include rocket-nginx/default.conf;

    listen 443;
    listen [::]:443 ssl;

    ssl on;
    ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    root /home/http/example.com/wordpress;
    index  index.php index.html index.htm;
    server_name *.example.com example.com;

    client_max_body_size 100M;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~* \.php$ {
            fastcgi_pass   fastcgi_backend;
            fastcgi_index index.php;
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

**Comment by maximejobin** [comment]
Well, based on what you've submitted, it's pretty hard to says why it is not working.

The configuration is installed on hundreds of websites... so it works. Now, what is wrong with your current setup is the question.

**Comment by maximejobin** [comment]
It would need an investigation directly on your server. Unfortunately, we cannot afford to do this for free. If interested, you can contact SatelliteWP for this: https://www.satellitewp.com/en/contact/

I'm sorry I could not give more information about your situation to help you fix this.
