### ISSUE TITLE
For url encoded slugs, Nginx is looking for uppercase files, but WP-Rocket is saving lowercase files

### ISSUE THREAD

**Issue by joke14** [SatelliteWP/rocket-nginx#147]
This is not an issue for english character only slugs.

But, if slugs have foreign characters, Nginx will look for the cache file with the uppercase version of the url encoded file name.

However, WP-Rocket is saving the cache file with the lowercase version of the url encoded filename.

For example, Wordpress is saving a file as %e0%b8%81 while Nginx is looking for %E0%B8%81

**Comment by maximejobin** [comment]
Can you elaborate on how I could reproduce the problem to see if it can be fixed?

Thank you.
