### ISSUE TITLE
Getting errors while implementing this

### ISSUE THREAD

**Issue by maxbizz** [SatelliteWP/rocket-nginx#150]
Hi got these errors even after trying the steps
nginx: [emerg] "set" directive is not allowed here in /etc/nginx/rocket-nginx/rocket-nginx.conf:17
nginx: configuration file /etc/nginx/nginx.conf test failed

My nginx version is 1.19.8

**Comment by maximejobin** [comment]
It is probably because of where you included the file.

I do not have enough information to help. Please provide more information about your setup and "how" and "where" you included the file.

**Comment by maximejobin** [comment]
No details provided.
