### ISSUE TITLE
Any updates coming that may support mobile caching?

### ISSUE THREAD

**Issue by flyize** [SatelliteWP/rocket-nginx#152]
From the FAQ, its clearly difficult to detect mobile devices. That said, mobile is the vast majority of client sites I see, so choosing between rocket-nginx and mobile caching isn't even a discussion. Any possible way to fix this?

**Comment by maximejobin** [comment]
Full support is impossible. That is why it was decided not to support mobile caching detection.

Aren't you using a responsive theme?

The fact that it is not supported by Rocket-Nginx means that it falls back to WP Rocket itself to manage it. I don't see that as an issue per se. It's just not as optimized as it could be.

**Comment by flyize** [comment]
Maybe I'm not understanding. I have to disable mobile caching to use rocket-nginx. Doesn't that mean wp-rocket that doesn't do anything for mobile devices?

**Comment by maximejobin** [comment]
Mobile cache is that it will save your page in 2 separate files: one for desktop, one for mobile. If your site is responsive (automatically adjust to the screen), you should not check this option.

**Comment by flyize** [comment]
Well, I sure do wish they would have written it like that. Thanks!

**Comment by flyize** [comment]
I just noticed an issue on a site, not sure if this needs a new issue open...

I turned off mobile caching in wp-rocket, enabled debug in rocket-nginx, and regenerated config. I'm still seeing things not cached and it shows the reason as mobile caching enabled.

Clearly I'm still doing something wrong. Any idea what I may have missed?

**Comment by flyize** [comment]
@maximejobin Anything you think I should try?

**Comment by maximejobin** [comment]
You don't have to regenerate the config. You must disable the option in WP Rocket and Clear the cache.

**Comment by flyize** [comment]
Yeah, I did all that and was still getting a No.

**Comment by maximejobin** [comment]
I will close this issue as there is no sign of this issue being a bug.
