### ISSUE TITLE
AutoScale on Amazon AWS

### ISSUE THREAD

**Issue by jeronimoramon** [SatelliteWP/rocket-nginx#154]
I would like to know if it is possible to use this configuration and wpRocket with a custom cache folder (pointing to an EBS volume) while the central wordpress directory is an EFS so that if necessary an autoScale rule starts new instances.
My question is whether the second instance would know that the cache does not exist and would recreate it

**Comment by jeronimoramon** [comment]
Hi, @maximejobin 
Actually what I'm trying to do is to get as far away from the EFS disk as it brings the necessary benefit of being able to be mounted in several instances, but it brings latency, so I thought of creating the cache outside the web directories, but not it will be possible.
I know it's out of scope, but do you know of any method for me to serve static files (js and css generated by WpRocket) through S3?
So I would escape the EFS latency

**Comment by maximejobin** [comment]
This is out of scope, as you say.

Using S3 will add even more latency. Your problem is simple... the solution is not! I had this problem in the past. ;-)

Good luck!
