### ISSUE TITLE
Still caching

### ISSUE THREAD

**Issue by SnAFKe** [SatelliteWP/rocket-nginx#157]
I have found a problem i did not notice until now and if you disable (not remove) wp-rocket still caching.

I'm not sure if this a bug or the nature of the nginx configuration. If you still have wp-rocket cache directory always looking cache file even is disable wp-rocket.

How to solve this issue? of course not deleting directory maybe for future use or when you want disable momentarily caching.

**Comment by maximejobin** [comment]
This is linked to a "problem" with WP-Rocket not deleting files after deactivation.

Rocket-Nginx serves the file if it exists. It cannot check if the plugin is activated or not.

Reference: https://github.com/wp-media/wp-rocket/issues/2500
