### ISSUE TITLE
When GZIP (.html_gzip) is enabled all html request is interpreted as downloads

### ISSUE THREAD

**Issue by newdreamglobal** [SatelliteWP/rocket-nginx#158]
Hi guys!

When implemented the last version of this rocket-nginx we got the same problem as reported on closed issue 
https://github.com/SatelliteWP/rocket-nginx/issues/50

when server response with the gzip version the browser download de file.
when remove the gzip version, the server response with the static html file just fine.

nginx version: 1.19.7
Rocket-Nginx version : 2.1.1
version of WP Rocket: 3.8.8
nginx as a webserver, not reverse proxy

We use CloudFlare as CDN on front of our nginx.

**Comment by maximejobin** [comment]
Can you send the provided headers and what was the response so this can be investigated?

This does not seem to be the same issue as what is described in #50.
