### ISSUE TITLE
I am getting REST api and loopback error 400

### ISSUE THREAD

**Issue by JoieHadinata** [SatelliteWP/rocket-nginx#159]
I am getting REST API encountered an expected result
The REST API call gave the following unexpected result: (400) <html> <head><title>400 Request Header Or Cookie Too Large</title></head> <body> <center><h1>400 Bad Request</h1></center> <center>Request Header Or Cookie Too Large</center> <hr><center>nginx</center> </body> </html> .

also
Your site cannot complete a loopback request
The loopback request returned an unexpected http status code, 400, it was not possible to determine if this will prevent features from working as expected.

Does anyone has idea ?
Joie

**Comment by maximejobin** [comment]
Does it work when Rocket-Nginx is disabled?

I do not see any link between your error and this project. Please provide more details.

**Comment by JoieHadinata** [comment]
With these settings i am getting  rest api and loopback error
large_client_header_buffers 2 1k;
rocket-nginx disable


With these settings i no longer have errors
large_client_header_buffers 4 32k;
rocket-nginx disable

With these settings i no longer have errors
large_client_header_buffers 4 32k;
rocket-nginx enable

So the problem was the large_client_header_buffers 2 1k;
my site is using woocommerce.

Thank you
Joie
