### ISSUE TITLE
WP-Rocket caches the file, but the cached file is not delivered

### ISSUE THREAD

**Issue by classbproject** [SatelliteWP/rocket-nginx#160]
Hi, thank you for creating this immensely useful tool. 

I've turned on the `debug` flag in the config file (with no other changes). In WP-Rocket I started preloading the cache and that went as expected. After a few minutes I could see all the pages being cached on the server (checked via the console). When I try `curl -I https://www.domain.com` the debugging headers show me that the page is cached and is being delivered. How this is true of only the homepage. While I can see that the other pages have indeed cached under `wp-content/cache/wp-rocket/www.domain.com` they are not being served to the visitor. With the curl command I see the following output. What am I missing here? 

```
HTTP/1.1 301 Moved Permanently
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 06 Jun 2021 08:20:49 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: PHPSESSID=a08du7vi6idtdv4av25156dm72; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Redirect-By: WordPress
Location: https://www.domain.com/resources/blogs/
X-Rocket-Nginx-Serving-Static: No
X-Rocket-Nginx-Reason: File not cached
X-Rocket-Nginx-File: /var/www/production/wp-content/cache/wp-rocket/www.domain.com//resources/blogs/index-https.html
```

This is what my domain specific config looks like under `sites-enabled`

```
server {
        server_name www.domain.com domain.com;

        root /var/www/production;
        index maint.html index.html index.htm index.php;
        charset UTF-8;

        ##
        # Server log config
        ##

        access_log off;
        error_log /var/log/exc_error.log warn;


        # Rocket-Nginx configuration
        include rocket-nginx/default.conf;

        ##
        # Favicon
        ##

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        ##
        # robots.txt
        ##

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }

        ##
        # Deny access to hidden files
        ##

        location ~ /\. {
            deny all;
        }

        ##
        # Deny access to uploaded PHP files
        ##

        location ~* /(?:uploads|files)/.*\.php$ {
            deny all;
        }

        ##
        # Deny access to WordPress include-only files
        ##

        location ~ ^/wp-admin/includes/ {
            deny all;
        }
        location ~ ^/wp-includes/[^/]+\.php$ {
            deny all;
        }
        location ~ ^/wp-includes/js/tinymce/langs/.+\.php {
            deny all;
        }
        location ~ ^/wp-includes/theme-compat/ {
            deny all;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name www.domain.com domain.com;
    return 404; # managed by Certbot
}
```

**Comment by classbproject** [comment]
Did some more digging! It seems WP_Rocket changed the file path format in version 3.9.0.1. I know this was tested with 3.8. The URL that Rocket-Nginx creates is 
```
/var/www/production/wp-content/cache/wp-rocket/www.domain.com/<parent-level-page>/<child-page>//index-https.html
```
However, the new WP Rocket now creates a path,
```
/var/www/production/wp-content/cache/wp-rocket/www.domain.com/<parent-level-page>/<child-page>/#q=/<parent-level-page>/<child-page>//index-https.html
```
There is an additional `#q=/<parent-level-page>/<child-page>/` in the path now.

**Comment by maximejobin** [comment]
WP Rocket 3.9 is not officially out yet.

Also, there is a redirect via the "Location" header in your request. The provided information is incomplete.

Can you tell me where you saw that the path format changed? I'm not aware of this...

**Comment by classbproject** [comment]
The latest version of WP Rocket that is installed seems to be `3.9.0.1`. This came as an auto update from them. 

![WP Rocket latest version](https://i.imgur.com/ggNkNp7.png)

Paths that the latest version of WP Rocket has generated on my server. I've also raised a support ticket with them to confirm this.

![Paths](https://i.imgur.com/shNMDVO.png)

> Also, there is a redirect via the "Location" header in your request.

Where is this? 

I'd be happy to provide more information If you need it.

**Comment by manuglopez** [comment]
Is there any solution to this issue?  I'm experiencing the same problem.

**Comment by maximejobin** [comment]
Get in touch with WP Rocket. Rocket-Nginx does not generate these folders.

**Comment by meow231a** [comment]
I'm using 3.9.0.1 and Rocket-Nginx works just fine. That path mentioned means you are caching query strings for some reason and those are the cache files for those query strings.

> There is an additional `#q=%2f<parent-level-page>%2f<child-page>%2f` in the path now.

I have some query strings I cache but I see those are not served through Rocket-Nginx, so this is really a feature request, not a bug.

**Comment by classbproject** [comment]
> Get in touch with WP Rocket. Rocket-Nginx does not generate these folders.

I did. They asked me to get in touch with you 🙄

**Comment by classbproject** [comment]
> I'm using 3.9.0.1 and Rocket-Nginx works just fine.
> 
> > There is an additional `#q=%2f<parent-level-page>%2f<child-page>%2f` in the path now.
> 
> That path means you are caching query strings and those are the cache files for those query strings.
> 
> I have some query strings I cache but I see those are not served through Rocket-Nginx, so this is really a feature request, not a bug. It is already being tracked here: #115

I thought this was the case too, however, my `cache query strings` field in WP Rocket is empty. From what I know I'm not caching any query strings.

**Comment by meow231a** [comment]
In your theme functions, you can have a line to enable caching of query strings. It doesn't have to be in WP Rocket settings.

If I were you, I would check if your non query string pages are cached. If they are, then Rocket-Nginx is working.

**Comment by classbproject** [comment]
So this was an issue with one of the location blocks in my nginx configuration. I've fixed that and this works great now. Thanks again for all the help on this.

**Comment by fidoboy** [comment]
> So this was an issue with one of the location blocks in my nginx configuration. I've fixed that and this works great now. Thanks again for all the help on this.

How did you solved it?

**Comment by classbproject** [comment]
If you see my original `nginx` configuration above, in the `location /` block you'll see `try_files $uri $uri/ /index.php?q=$uri&$args;`. This was causing WP-Rocket to add another level of folder in the directory structure that WP-Rocket couldn't recognise. It kept looking for the static HTML at this level but in fact, it was in the folder one level deeper that my `nginx` configuration created. I changed that to `try_files $uri $uri/ /index.php?$args;` and now it works fine.
