### ISSUE TITLE
Does this support Nginx in reverse proxy mode?

### ISSUE THREAD

**Issue by dciphered** [SatelliteWP/rocket-nginx#162]
Hi,

Does this configuration work if nginx is configured as a reverse proxy for Apache?

We're running the Plesk hosting panel which by default utilises an nginx reverse proxy configuration for vhosts. htaccess rules play a big part on our site so a complete switch over to nginx in web server mode won't work for us.

Many thanks in advance.

**Comment by maximejobin** [comment]
It really depends on how your reverse proxy is configured.

In most setup I've seen, Nginx is configured to serve only some specific static file extensions. That way, it won't work.

So it is not impossible but it really depends on how it was configured.
