### ISSUE TITLE
no headers with cloudflare

### ISSUE THREAD

**Issue by cloudcreatr** [SatelliteWP/rocket-nginx#164]
there is no headers seen when i enable cloudflare on my site. its not working

**Comment by maximejobin** [comment]
More details are needed. What is the website? Why do you claim this is caused by Rocket-Nginx.

We use Cloudflare and the headers are displayed properly.

**Comment by cloudcreatr** [comment]
i was only able to see headers when visiting through ip and but now its solved i created a config for my domain
