### ISSUE TITLE
WP Rocket / Nginx / Cloudflare problem

### ISSUE THREAD

**Issue by AdamiPL** [SatelliteWP/rocket-nginx#165]
Hej,

i have configured cloudflare related to wp rocket tutorials but when i have cloudflare on, then:
x-rocket-nginx-reason: File not cached

if i pause using cloudflare caching starts working...

I have created a page rule on cloudflare:

```
upgrademyaudi.net/*
Cache Level: Bypass, Origin Cache Control: On
```

but it sill won't work..
i really need cloudflare and you to work together..

This is when i using cloudflare:
```
server: cloudflare
vary: Accept-Encoding
x-cache-status: BYPASS
x-powered-by: PHP/8.0.10
x-powered-by: PleskLin
x-rocket-nginx-file: /var/www/vhosts/updatemynav.com/upgrademyaudi.net/wp-content/cache/wp-rocket/upgrademyaudi.net/return-policy/index.html_gzip
x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No
```

and this when i pause cloudflare:

```
Server: nginx
vary: Accept-Encoding
x-cache-status: MISS
X-Powered-By: PleskLin
X-Rocket-Nginx-File: /var/www/vhosts/updatemynav.com/upgrademyaudi.net/wp-content/cache/wp-rocket/upgrademyaudi.net/return-policy/index-https.html
X-Rocket-Nginx-Reason: /wp-content/cache/wp-rocket/upgrademyaudi.net/return-policy/index-https.html
X-Rocket-Nginx-Serving-Static: Yes

```
I am using plesk on centos 8..

im now giving up after whole day of a "war".. maybe you will help me to solve this problem :(

**Comment by maximejobin** [comment]
I know many people had some problems configuring Plesk to work properly. I personally do not use Plesk.

I recommend checking this issue:
https://github.com/SatelliteWP/rocket-nginx/issues/117
