### ISSUE TITLE
rocket-nginx not serving any page

### ISSUE THREAD

**Issue by fidoboy** [SatelliteWP/rocket-nginx#167]
My nginx conf is as follows:

`
server {
	listen 000.000.000.000:443 ssl ;
	server_name myserver.com  www.myserver.com;
	access_log /usr/local/apache/domlogs/myserver.com.bytes bytes;
	access_log /usr/local/apache/domlogs/myserver.com.log combined;
	error_log /usr/local/apache/domlogs/myserver.com.error.log error;

	ssl_certificate      /etc/pki/tls/certs/myserver.com.bundle;
	ssl_certificate_key  /etc/pki/tls/private/myserver.com.key;
	ssl_protocols TLSv1.2;
	ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA!RC4:EECDH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;
	ssl_prefer_server_ciphers   on;

	ssl_session_cache   shared:SSL:10m;
	ssl_session_timeout 60m;

	# Rocket-Nginx configuration
	include /etc/nginx/rocket-nginx/default.conf;

	location / {
		location ~.*\.(3gp|gif|jpg|jpeg|png|ico|wmv|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|html|htm|txt|js|css|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|woff|woff2|ttf|svg|eot|sh|webp)$ {
			root /home/myserver/public_html;
			expires max;
			try_files $uri $uri/ @backend;
		}
		
		error_page 405 = @backend;
		error_page 500 = @custom;
		add_header X-Cache "HIT from Backend";
		add_header Strict-Transport-Security "max-age=31536000";
		add_header X-XSS-Protection "1; mode=block" always;
		add_header X-Content-Type-Options "nosniff" always;
		proxy_pass http://000.000.000.000:82;
		include proxy.inc;
	}

	location @backend {
		internal;
		proxy_pass http://000.000.000.000:82;
		include proxy.inc;
	}

	location @custom {
		internal;
		proxy_pass http://000.000.000.000:82;
		include proxy.inc;
	}

	location ~ .*\.(php|jsp|cgi|pl|py)?$ {
		proxy_pass http://000.000.000.000:82;
		include proxy.inc;
	}

	location ~ /\.ht    {deny all;}
	location ~ /\.svn/  {deny all;}
	location ~ /\.git/  {deny all;}
	location ~ /\.hg/   {deny all;}
	location ~ /\.bzr/  {deny all;}

	disable_symlinks if_not_owner from=/home/myserver/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}
}`

But I'm not getting the rocket-nginx headers in my frontend (there is however a header in wp-admin pages "x-rocket-nginx-serving-static: No")

Wo what's wrong in my setup?

**Comment by maximejobin** [comment]
There are not enough information here to know what's wrong.

Did you follow the configuration guide?
