### ISSUE TITLE
Cache-Control header Leverage browser caching

### ISSUE THREAD

**Issue by furchtlos76** [SatelliteWP/rocket-nginx#169]
First thank you so much for this great plugin, i really hope development is going on and version 3 will be released some time. I got some strange problem. https://webpagetest.org and others are showing me, browser cache is not active for example for www.wt-tun.de

In rocketnginx config its there:
###################################################################################################
# BROWSER CSS CACHE
#
location ~* \.css$ {
        etag on;
        gzip_vary on;
        expires 30d;

}

###################################################################################################
# BROWSER JS CACHE
#
location ~* \.js$ {
        etag on;
        gzip_vary on;
        expires 30d;

}

###################################################################################################
# BROWSER MEDIA CACHE
#
location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg)$ {
        etag on;
        expires 30d;

}

-------------------------------------------------
does anyone got an idea what to change else? using plesk

**Versions**
What version of Nginx are you using: latest
What version of Rocket-Nginx are you using : latest
What version of WP Rocket are you using: latest
Are you using Nginx as a reverse proxy (with Apache for instance): yes

**Comment by maximejobin** [comment]
For help with Plesk, please see:
https://github.com/SatelliteWP/rocket-nginx/issues/117
