### ISSUE TITLE
In version 3 I see images are not cached

### ISSUE THREAD

**Issue by taikhoancapcao** [SatelliteWP/rocket-nginx#175]
![2022-01-16 054916](https://user-images.githubusercontent.com/71458384/149640077-f88ebc7d-048b-44b0-be88-79251ae9a62f.png)

In version 3 I see images are not cached.
I don't understand the config file you suggested below:
Before Rocket-Nginx starts
In the default profile, create a file in the conf.d/default/ having the following filename pattern : start.*.conf.

Globally in every section
In the default profile, create a file in the conf.d/default/ having the following filename pattern : global.*.conf.

In the HTTP section
In the default profile, create a file in the conf.d/default/ having the following filename pattern : http.*.conf.

In the CSS section
In the default profile, create a file in the conf.d/default/ having the following filename pattern : css.*.conf.

In the JS section
In the default profile, create a file in the conf.d/default/ having the following filename pattern : js.*.conf.

In the Media section
In the default profile, create a file in the conf.d/default/ having the following filename pattern : media.*.conf.

Thank you very much!

**Comment by maximejobin** [comment]
Per your screenshot, it is cached for 30 days:
![image](https://user-images.githubusercontent.com/1080760/150387192-9421ef83-1e69-4613-bc8c-f8681bb1c5cb.png)

This can be edited from the config file without creating any new file.

The Rocket-Nginx header is misleading as Rocket-Nginx simply edits the the expiration but does not "cache" the image. There is no point in doing that as it is already a static file. I might reconsider adding the header for medias.

**Comment by taikhoancapcao** [comment]
Thank you very much for taking the time to answer my question. Wish you always have health, happiness and success in life.
