### ISSUE TITLE
Suggested Setup with Cloudflare?

### ISSUE THREAD

**Issue by jordantrizz** [SatelliteWP/rocket-nginx#178]
This isn't a bug, but more looking for answers on the recommended method for using Rocket Nginx with Cloudflare.

**Comment by maximejobin** [comment]
There is nothing to do.

We use Cloudflare and there is nothing special if you're using it too!

**Comment by jordantrizz** [comment]
Are you using the WP Rocket preloading feature?

I'm asking because I've seen a site behind Cloudflare with Rocket Nginx setup continually getting MISS due to traffic not hitting the origin as Cloudflare was holding a cache of the page.

Once the page is purged from the Cloudflare cache, the page is visited by a client. The cache for the page is generated by WP Rocket.

So this results in the cache not being used until such time as Cloudflare passes the traffic through to the origin.
