### ISSUE TITLE
PHP Warning:  Module 'brotli' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by ufo86817** [SatelliteWP/rocket-nginx#180]
PHP Warning:  Module 'brotli' already loaded in Unknown on line 0
What should I do if this problem occurs during installation?

**Comment by maximejobin** [comment]
This has nothing to do with Rocket-Nginx and is linked to your php.ini file.

If you run any PHP file from the command line, you'll probably get the same error. Rocket-Nginx does not use the brotli module.

You can check this question on Stackoverflow that is similar to your problem:
https://stackoverflow.com/questions/32764981/php-warning-module-already-loaded-in-unknown-on-line-0
