### ISSUE TITLE
Doesn't work on localhost when port is included in the url

### ISSUE THREAD

**Issue by saberkarimi** [SatelliteWP/rocket-nginx#183]
Hi. I am using the latest version,
I am working on my website on localhost via WSL (windows subsystem for Linux).
My homepage URL is: https://localhost:83
I need to include the port because that is how Nginx works on WSL.

This is what I get in debug as file location:
X-Rocket-Nginx-File: /var/www/imp/wp-content/cache/wp-rocket/localhost:83//fr///index.html
X-Rocket-Nginx-Reason: File not cached
X-Rocket-Nginx-Serving-Static: MISS

You see the port # is included in the path. But in my "/wp-content/cache/wp-rocket/" folder, only "localhost" is created as folder. No "localhost:83" and therefore static files can not be served.

Any help would be appreciated
Kind regards

**Comment by maximejobin** [comment]
That is interesting.

I've never tested with a port... so good catch.

The question now is : is it worth fixing this? Clearly "localhost" is for development purposes and not for production.

Why do you need that use case to work?

**Comment by saberkarimi** [comment]
You are right this is not worth fixing. I moved this specific project to a droplet. All good.

Thanks
