### ISSUE TITLE
# Add header to HTML cached files working only on some domains

### ISSUE THREAD

**Issue by furchtlos76** [SatelliteWP/rocket-nginx#185]
**Describe the bug**

Even rocket is shown used in Header with HIT, i dont get additional headers added to most of my websites. On some it works, on others it does not add those headers. I am using the following config:

# Add header to HTML cached files
location ~ /wp-content/cache/wp-rocket/.*html$ {
        etag on;
        add_header Vary "Accept-Encoding, Cookie";
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
        add_header X-Rocket-Nginx-Reason $rocket_reason;
        add_header X-Rocket-Nginx-File $rocket_file;
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "strict-origin-when-cross-origin";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

**Versions**
What version of Nginx are you using ?
What version of Rocket-Nginx are you using ? 3.0
What version of WP Rocket are you using ? latest 
Are you using Nginx as a reverse proxy (with Apache for instance) ? yes

**To Reproduce**
Steps to reproduce the behaviour:

Non working site: (Headers NOT added)
https://webbkoll.dataskydd.net/de/results?url=http%3A%2F%2Ftheaterverein-dogern.de

Working site: (Headers added)
https://webbkoll.dataskydd.net/de/results?url=http%3A%2F%2Fsonnenhof-reha.de

Both use the same config of rocket-nginx and both use ist, as x-rocket-nginx headers are there, just other headers are missing on one site. Any idea what could be the couse of this?

**Comment by maximejobin** [comment]
I see the right headers on both sites.

**Comment by furchtlos76** [comment]
> I see the right headers on both sites.

How that? I still see one site those variables i wrote like:

add_header Cache-Control "no-cache, no-store, must-revalidate";
add_header X-Content-Type-Options "nosniff";
add_header Referrer-Policy "strict-origin-when-cross-origin";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";

are added and on the other site not. Now i see in your 3.0 changelog:

"Allowing adding headers from the config file was removed."

Has this maybe something to do with it?

**Comment by furchtlos76** [comment]
I installed Rocket Nginx now from start again, and i can confirm, its still the same. With default config, no headers are added. Whith my config with added headers, on some sites it does use those add_header commands from the config file, and on others not, and i could not find out why. I dont know guthub very good, but do you get this messages even the issue is closed?

**Comment by maximejobin** [comment]
You do not have to reinstall anything... you are simply not looking at the right place:

![image](https://user-images.githubusercontent.com/1080760/195678280-e04e1564-523c-49f0-9237-064e19ddaee3.png)

Simply click on both links you provided:

> Non working site: (Headers NOT added)
> https://webbkoll.dataskydd.net/de/results?url=http%3A%2F%2Ftheaterverein-dogern.de
>
> Working site: (Headers added)
> https://webbkoll.dataskydd.net/de/results?url=http%3A%2F%2Fsonnenhof-reha.de

Then with `Ctrl-F`, search for `rocket` and you will get to the section in the screenshot.

**Comment by furchtlos76** [comment]
No, sorry you got me wrong, i dont talk about the Rocket Headers - as i said both sites are fine and add the rocket headers with HIT. I am talking about OTHER headers i added in the Section add headers in the configuration:

in 

# Add header to HTML cached files

i added:

add_header Cache-Control "no-cache, no-store, must-revalidate";
add_header X-Content-Type-Options "nosniff";
add_header Referrer-Policy "strict-origin-when-cross-origin";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";

And on some sites they where added and on others not. 
In your Documentation for 3.0 you wrote:

What is new in version 3.x? **Allowing adding headers from the config file was removed.**

Maybe this has something to do with that. Well dont mind, i moved my extra headers outside of the configuration file and inside nginx configuration and that works now.

**Comment by furchtlos76** [comment]
I found the sollution, for anyone else having the same problem on plesk: https://talk.plesk.com/threads/nginx-browser-caching-for-static-resources.334497/#post-790630 - you have to remove html/htm from "serve static files with nginx..." box. Then it will  proceed to the directives in vhost_nginx.conf or rocket-nginx and add the extra headers.

But i still dont understand what is ment by:

"What is new in version 3.x? **Allowing adding headers from the config file was removed.**"
