### ISSUE TITLE
Add CSP to single domains when server is using Rocket Nginx

### ISSUE THREAD

**Issue by furchtlos76** [SatelliteWP/rocket-nginx#187]
Hi, i am still trying to add some Content-Security-Policys to nginx on single domains.
On all my WP Projects i use rocket-nginx. 

In Plesk it is included per domain in "Additional nginx directives". Everything works fine but i am still trying to add some
extra headers also to the content that is cached and delivered by nginx. What is the best practice for this, if i dont want to add this globaly to all domains? When i add it inside default.conf it works ofcause, but for all domains that use rocket-nginx.

If i add it like this inside "Additional nginx directives": 

add_header Content-Security-Policy "font-src 'self'";
add_header Content-Security-Policy "style-src 'self'";
include rocket-nginx/default.conf;

or 

include rocket-nginx/default.conf;
add_header Content-Security-Policy "font-src 'self'";
add_header Content-Security-Policy "style-src 'self'";

the extra headers like font-src self or style-src self are not added as soon as include rocket-nginx/default.conf; does include rocket-nginx. Does anyone maybe has an idea how to add extra headers per domain?

**Comment by maximejobin** [comment]
You should use the `default.conf` for all your websites... except the one you want to be different.

At the end of `rocket-nginx.ini`, simply add this:

    [newsite : default]

Then, run the PHP parser:

    php rocket-parser.php

In your `conf.d` folder, you should see a folder named `newsite`. Inside this folder, simply create a file named `global.my_new_headers.conf` and add your header rules in it.

Once you are done, make sure to test the configuration to make sure there are no mistakes. (`nginx -t)

Then, reload the Nginx configuration. (`service nginx reload`)

You are done!

**Comment by furchtlos76** [comment]
Thanks alot for your help!!! But isn't it for alle sites then, too if i add it there? or is "newsite" the name of my domain for example? or shouild i use different rockjet-nginx.ini one per domain?
