### ISSUE TITLE
No file located

### ISSUE THREAD

**Issue by kevin25** [SatelliteWP/rocket-nginx#194]
**Describe the bug**

 set $rocket_debug 1; but nothing shows up.

<img width="1950" alt="Screen Shot 2023-05-05 at 22 38 25" src="https://user-images.githubusercontent.com/2909982/236505531-1fd28072-6c96-4efa-813c-f29f4224feb3.png">
I'm using 

nginx version: nginx/1.23.1

**Versions**
What version of Nginx are you using ?
What version of Rocket-Nginx are you using ?
What version of WP Rocket are you using ?
Are you using Nginx as a reverse proxy (with Apache for instance) ?

**To Reproduce**
Steps to reproduce the behaviour:

Did you activate the debug in Rocket-Nginx ? Please do and include any headers.

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.

**Expected behavior**

**Additional context**

**Comment by maximejobin** [comment]
Looking at your screenshot, there is no sign of Rocket-Nginx (and there should be no matter if you activate debug or not).

It seems that you:
1) Maybe did not generate the configuration with `rocket-parser.php`
2) Maybe did not include your generated configuration at the right place in your Nginx configuration
3) Maybe did not reload Nginx's configuration (ex: `service nginx reload`)

**Comment by kevin25** [comment]
I'm using WooCommerce. I can see it when admin is logged. I can't see it when i'm browsing as guest.

**Comment by maximejobin** [comment]
> I can see it when admin is logged.

What can you see?

If you cannot see any Rocket-Nginx header, it means the script is not installed or configured properly.
