### ISSUE TITLE
Cache-Control values could support bfcache usage?

### ISSUE THREAD

**Issue by E-VANCE** [SatelliteWP/rocket-nginx#197]
This isn't a bug – more of a feature request / question regarding the current `Cache-Control`-implementation...

Having read up on the browser [bfcache](https://web.dev/bfcache) this morning and testing our site with Chrome's Dev Tools, I found it isn't comaptible due to `no-cache, no-store, must-revalidate`.

By default WP Rocket seems to be using `max-age=0` and that allows for the bfcache to be applied.

I have adjusted the template file accordingly but was wondering if you see any major downsides when it comes to tweaking the `Cache-Control`-header in this fashion?

Or maybe the `max-age=0` could become the default and all sites would benefit from a bfcache...?

Thanks a lot for providing this config, very helpful! 🙏

**Comment by maximejobin** [comment]
> I have adjusted the template file accordingly

Is there a reason for changing the template instead of editing the configuration file?

You can change the `Cache-Control` and add headers by simply editing the configuration. No need to edit the template.

That being said, I will take a look and see if/how the project can be improved!

**Comment by maximejobin** [comment]
After reading on BF Cache and the needed modifications, I'm happy to say that Rocket-Nginx is already compatible with BF Caching!

All you have to do is to change the line in your `rocket-nginx.ini` configuration from:

    html_cache_control = "no-cache, no-store, must-revalidate"

To:

    html_cache_control = "no-cache, must-revalidate"

Then, run the `rocket-parser.php` file again, reload the Nginx configuration, and you're done!

For security reasons, I will not change the default configuration to make it compatible with BF Cache. It will be up to the server administrator to validate if the website can have its data in cache.

I tested it on my personal website and it works as shown from the **Dev Console > Application** tab under the **Back/forward cache** section (under Background services).

![image](https://github.com/SatelliteWP/rocket-nginx/assets/1080760/652d0114-2662-4ea0-8413-4b8d6f950bc0)
