### ISSUE TITLE
Information about the Rocket-Nginx installation in the server

### ISSUE THREAD

**Issue by Feruz7777** [SatelliteWP/rocket-nginx#198]
Hello Mr Jobin, I hope you are well.

I am addressing you regarding the Rocket-Nginx configuration on my server which is administered by Plesk.

Indeed, I read the information that you put on the site https://github.com/SatelliteWP/rocket-nginx and before installation I would like to ask you about my Virtual Dedicated Server I use Almalinux 8 and my question is Rocket-Nginx compatible with my server?
Then Rocket-Nginx will be used on my server without WP Rocket plugin or will it have to be installed on my site WordPress ?

Thanks for your answer.
Sincerely,
Feruz.

**Comment by maximejobin** [comment]
> I would like to ask you about my Virtual Dedicated Server I use Almalinux 8 and my question is Rocket-Nginx compatible with my server?

The OS has no impact on Rocket-Nginx. If you can run Nginx and WP Rocket, you are good to go. Of course, you'll need PHP too... but as you are running a WordPress website, PHP should already be installed on your server.

> Then Rocket-Nginx will be used on my server without WP Rocket plugin or will it have to be installed on my site WordPress ?

Rocket-Nginx simply serves cached files created by WP Rocket more efficiently. Therefore, it cannot run without WP Rocket.

I hope this helped!

**Comment by Feruz7777** [comment]
Hello,

Thank you very much for your precise answer. 

Then, I have another question, in fact, on my server the Nginx functionality is already activated by default by Plesk and my question is Rocket-Nginx and Plesk Nginx give the same functionality or their features are different? If their functionalities are different then should I disable the Plesk Nginx functionality or should I leave it as it is?
