### ISSUE TITLE
Difference to fastcgi cache

### ISSUE THREAD

**Issue by Askotion** [SatelliteWP/rocket-nginx#199]
Hi,

im trying to implement this in our stack. Currently we run a fastcgi cache with the Nginx cache disable plugin for WP Rocket. 
It should not be used together, right? So either rocket-nginx cache or fastcgi cache?
Will there be a difference in using rocket-nginx over fastcgi cache? It should both serve static cache before php / Wordpress. 

Thank you!

**Comment by maximejobin** [comment]
There is no point in using Nginx caching if you use WP Rocket + Rocket-Nginx.

The main difference will be that it is a lot easier to pick what should be in cache and what not from WP Rocket + Rocket-Nginx than it will be from manually configuring Nginx cache. This also depends on what is done on your website.

With Rocket-Nginx, cached files are served as static file, without executing PHP and WordPress.
