### ISSUE TITLE
DEV use this repo for mobile / desktop cache wp-rocket activated!

### ISSUE THREAD

**Issue by roblernsehen** [SatelliteWP/rocket-nginx#200]
I went here because I forked your /etc/nginx/rocket-nginx/conf.d/default.conf to work with mobile / desktop cache when you activate wp-rocket seperate mobile cache.

**I want to ask you guys and repo owner if you see any downside with this fork?**

-----
**Please use it not for production unless you test everything and make it persistent.**
**Please use it not for production unless you test everything and make it persistent.**
**Please use it not for production unless you test everything and make it persistent.**
-----

It is not ready yet for production and we're testing it slowely on a smaller woocommerce store with around 3000 unique visitors daily.

I found out that this small repo is bypassing a lot of requests to wp-rocket and php when mobile cache activated (you described it) and also when you have woocommerce in the background with wc cookies.

So if you want this config working with woocommerce you have to switch this block with your need and remove all woocommerce cookies from the block, for example ours:

```
#Do not bypass if one of those cookie if found
#wordpress_logged_in_[hash] : When a user is logged in, this cookie is created (we'd rather let WP-Rocket handle that)
#wp-postpass_[hash] : When a protected post requires a password, this cookie is created.
if ($http_cookie ~* "(wordpress_logged_in_|wp\-postpass_|wptouch_switch_toogle|comment_author_|comment_author_email_)") { ....
```

If you want to handle mobiel / desktop HIT by this repo, you can add this to your nginx http config for your host at the top, but still inside nginx.conf http {...} block!
Be careful with your ipad tablet cache file.

```
map $http_user_agent $mobile_request {
 default                  fullversion;

 "~*ipad"    mobileversion;
 "~*android.*mobile"   mobileversion;
 "~*iphone"    mobileversion;
 "~*ipod.*mobile"   mobileversion;
 "~*BlackBerry*Mobile Safari"  mobileversion;
 "~*BB*Mobile Safari"   mobileversion;
 "~*Opera.*Mini/7"   mobileversion;
 "~*IEMobile/10.*Touch"   mobileversion;
 "~*IEMobile/11.*Touch"   mobileversion;
 "~*IEMobile/7.0"   mobileversion;
 "~*IEMobile/9.0"   mobileversion;
 "~*Firefox.*Mobile"   mobileversion;
 "~*webOS"    mobileversion;
}
```

within  /etc/nginx/rocket-nginx/conf.d/default.conf I added this right under 
`# Standard cache file format
`
#ADD THIS
```
#Standard mobile cache file format
set $rocket_mobilefile_start "index-mobile$rocket_https_prefix";
set $rocket_mobile_url "$rocket_pre_url$rocket_mobilefile_start$rocket_dynamic.html";
set $rocket_mobile_file "$rocket_pre_file$rocket_mobilefile_start$rocket_dynamic.html";
```

#AFTER THAT ADD THIS

```
set $mobile_cache_found 0;
#check for what to look for mobile or desktop
if ($mobile_request = "mobileversion") {
        set $rocket_file $rocket_mobile_file;
        set $rocket_url $rocket_mobile_url;
}
```

when you now want to test, you need to uncomment this:

```
if (-f "$rocket_mobile_detection") {
        set $rocket_bypass 0;
        set $rocket_is_bypassed "BYPASS";
        set $rocket_reason "Specific mobile cache activated";
}
```

to this:

```
#if (-f "$rocket_mobile_detection") {
#      set $rocket_bypass 0;
#        set $rocket_is_bypassed "BYPASS";
#       set $rocket_reason "Specific mobile cache activated";
#}
```

**Comment by maximejobin** [comment]
I totally understand the reason why you did all this.

The main problem is that what you started is incomplete and will always be incomplete because the "Nginx scripting language" is really incomplete and it is not possible to do everything you need to get the job done.

A couple of years ago, I started a sub-project where I tried to tackle this exact problem. I stopped after realizing that it would hardly do what it is supposed to do.

Will it work for "most" visitors? Probably. But this seems more like an experimentation than a "production-ready" project.

You can take a look at it:
https://github.com/maximejobin/nginx-mobile

Good luck!
