### ISSUE TITLE
wp-admin 403 error

### ISSUE THREAD

**Issue by wurkagency** [SatelliteWP/rocket-nginx#201]
**Describe the bug**
When using the script, /wp-admin becomes inaccessible with a NGINX 403 error.

**Versions**
Nginx
Rocket-Nginx: v.3
WP Rocket: v.3.15.1
Nginx Setup: Reverse Proxy

**To Reproduce**
Implement and vóila.

** Configuration / source NGINX config** 
latest source as per yesterday.

**Expected behavior**
Working administration :)

**Comment by maximejobin** [comment]
Unfortunately, the problem you are describing has nothing to do with Rocket-Nginx.

The configuration serves a file from cache only if it exists. Otherwise, it does nothing. The `wp-admin` is never put in cache by WP Rocket (or any other caching plugin I know).

The problem is somewhere else.
