### ISSUE TITLE
apache and mod_rewrite

### ISSUE THREAD

**Issue by fidoboy** [SatelliteWP/rocket-nginx#202]
I've noticed that WP Rocket adds a section with mod_rewrite rules to get the cache file bypassing WordPress. My question is: does rocket-nginx works if this rule is removed? It's needed to get rocket-nginx doing his work? My setup is nginx configured as reverse proxy and apache with php-fpm

**Comment by maximejobin** [comment]
In theory, if Nginx is used as a reverse proxy, it will be called before Apache. Therefore, I don't think you need to alter anything.
