### ISSUE TITLE
Multilang

### ISSUE THREAD

**Issue by lukapaunovic** [SatelliteWP/rocket-nginx#205]
It does not support multilanguage pages.

**Comment by lukapaunovic** [comment]
example of cache files:

index-https-RON-RON.html  index-https-RON-RON.html_gzip  index-mobile-https-EUR-EUR.html  index-mobile-https-EUR-EUR.html_gzip

**Comment by fidoboy** [comment]
I've reported this issue on another thread. It seems that rocket-nginx doesn't take the dynamic cookies into consideration. I believe that it's necessary a new feature into next release to allow setup for dynamic cookies like this one for language or many others.

**Comment by maximejobin** [comment]
Duplicate of https://github.com/SatelliteWP/rocket-nginx/issues/204
