### ISSUE TITLE
Issue with Brotly compression

### ISSUE THREAD

**Issue by fidoboy** [SatelliteWP/rocket-nginx#206]
Right now there is NO support into WP Rocket for Brotli compression. I can't understand why but the case is what it is: there is only support for gzip. The issue is that into the rocket-nginx nginx code it checks for http accept encoding headers and if there is then it disables the gzipped files output.

This is an undesired behaviour because if the client browser supports broli it also supports gzip and then it shouldn't be disabled as it's right now but keep it enabled to serve the file with the right extension. So the Brotli check only should be made when WP Rocket has support for Brotli and it creates also the Brotli files (as it's doing right now with gzip and adding it into the filename)

**Comment by maximejobin** [comment]
> This is an undesired behaviour because if the client browser supports broli it also supports gzip 

That statement is not true.

> The issue is that into the rocket-nginx nginx code it checks for http accept encoding headers and if there is then it disables the gzipped files output.

Here is a call made to validate Brotli works:

`curl -I -H 'Accept-Encoding: gzip, deflate' https://www.satellitewp.com`

    HTTP/2 200 
    date: Tue, 07 Nov 2023 14:52:25 GMT
    content-type: text/html
    last-modified: Tue, 07 Nov 2023 06:10:48 GMT
    vary: Accept-Encoding
    vary: Accept-Encoding, Cookie
    cache-control: no-cache, no-store, must-revalidate
    x-rocket-nginx-serving-static: HIT
    strict-transport-security: max-age=15768000
    cf-cache-status: DYNAMIC
    report-to: <manually stripped>
    server: cloudflare
    cf-ray: 82266664abf636b7-YYZ
    content-encoding: gzip <====================== Gzip is working
    alt-svc: h3=":443"; ma=86400

Here is a call made to test Brotli:

`curl -I -H 'Accept-Encoding: gzip, br' https://www.satellitewp.com`

HTTP/2 200 
date: Tue, 07 Nov 2023 14:54:55 GMT
content-type: text/html
last-modified: Tue, 07 Nov 2023 06:10:48 GMT
vary: Accept-Encoding
vary: Accept-Encoding, Cookie
cache-control: no-cache, no-store, must-revalidate
x-rocket-nginx-serving-static: HIT
strict-transport-security: max-age=15768000
cf-cache-status: DYNAMIC
report-to: <manually stripped>
server: cloudflare
cf-ray: 82266a09cdada240-YYZ
content-encoding: br <====================== Brotli is working
alt-svc: h3=":443"; ma=86400


For some reason, the WP Rocket developers decided to save a "gzipped" file to serve it without having to zip it on the fly. They did not code anything for Brotli, so Rocket-Nginx lets the server handle the compression.

I do not see any issue here.

What is the problem exactly?

**Comment by eilandert** [comment]
I tested it with br and zstd, no issues here ;-)
