### ISSUE TITLE
WP Rocket / Best configuration example

### ISSUE THREAD

**Issue by stefanbiba** [SatelliteWP/rocket-nginx#210]
Hi,

As I want to give my users the best user experience for my website, are there any „best configuration“ examples of WP Rocket in combination with default rocket-nginx setup? I know that there is no „best configuration for all WP instances” but maybe a good start to work with. I haven’t found sthg online but maybe this question has been asked in the past :-) Thank you

**Comment by maximejobin** [comment]
The configuration is made to be optimized out-of-the-box. If you follow the documentation and sections "Before you start" and "Installation". You're good!

Then, everything else is specific to your website.

If you want to challenge yourself, read about every option in WP Rocket and every configuration in Rocket-Nginx to know if you should use them differently (in other words, edit the default value).

In my own usage, I rarely edit more than 2-3 variables... if any.

I hope this helped!
