### ISSUE TITLE
webp function seems not enabled

### ISSUE THREAD

**Issue by philbraun** [SatelliteWP/rocket-nginx#213]
**Describe the bug**
When WP Rocket has Add-Ons > WebP Compatibility set to ON, the cache files generated (for latest MS Edge browser) are set correctly to index-https-webp.html.
However, NGiNX is searching for index-https.html with rocket-nginx enabled, which results on Cache MISS.

Solution is to disable WPRocket's webp add-on, and enable it e.g. in Shortpixel's Image Optimizer.
Now the generated cache files will be index-https.html, which NGiNX fill find resulting in cache HITs.

**Versions**
What version of Nginx are you using ?
1.24.0
What version of Rocket-Nginx are you using ?
3.0.2
What version of WP Rocket are you using ?
3.15.10
Are you using Nginx as a reverse proxy (with Apache for instance) ?
no

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a server with spinupwp, add WP site, add rocket-nginx

Did you activate the debug in Rocket-Nginx ? Please do and include any headers.
X-Content-Type-Options:
nosniff
X-Frame-Options:
SAMEORIGIN
X-Rocket-Nginx-File:
/sites/mysite/files/wp-content/cache/wp-rocket/mysite//fr/directory///index-https.html
X-Rocket-Nginx-Reason: File not cached
X-Rocket-Nginx-Serving-Static: MISS

Files created by Rocket:
/sites/mysite/files/wp-content/cache/wp-rocket/mysite//fr/directory///index-https-webp.html (and index-https-webp.html_gzip)

Make sure you include ALL Nginx configuration files you are using. Remove any sensitive information before submitting.
generated default.conf:

        ###################################################################################################
        # Rocket-Nginx
        #
        # Rocket-Nginx is a NGINX configuration to speedup your WordPress
        # website with the cache plugin WP-Rocket (http://wp-rocket.me)
        #
        # Author: Maxime Jobin
        # Maintainer: SatelliteWP.com
        # URL: https://github.com/satellitewp/rocket-nginx
        #
        # Tested with WP-Rocket version: 3.14.4.2
        # Tested with NGINX: 1.25.2 (mainline)
        #
        # Version 3.0.2
        #
        ###################################################################################################
        
        # Add debug information into header
        set $rocket_debug 0;
        
        
        ###################################################################################################
        # Do not alter theses values
        #
        set $rocket_bypass          1;      # Should NGINX bypass WordPress and call cache file directly ?
        set $rocket_encryption      "";     # Is GZIP accepted by client ?
        set $rocket_file            "";     # Filename to look for
        set $rocket_is_bypassed     "MISS"; # Header text added to check if the bypass worked or not. Header: X-Rocket-Nginx-Serving-Static
        set $rocket_reason          "";     # Reason why cache file was not used. If cache file is used, what file was used
        set $rocket_https_prefix    "";		# HTTPS prefix to use when cached files are using HTTPS
        set $rocket_has_query_cache 0;		# Checks if a query string from URL is found from the cached query string
        set $rocket_is_https        0;		# Checks if the request is HTTPS
        set $rocket_support_webp    0;		# Checks if the request supports WebP
        set $rocket_dynamic         "";		# Dynamic value to add to cached filename
        
        ###################################################################################################
        # PAGE CACHE
        #
        
        include /etc/nginx/rocket-nginx/conf.d/default/start.*.conf;
        
        # Define Rocket-Nginx $is_args
        set $rocket_is_args $is_args;
        
        set $rocket_uri_path "";
        if ($request_uri ~ "^([^?]*)(\?.*)?$") {
	        set $rocket_uri_path $1;
        }
        
        # Is GZIP accepted by client ?
        if ($http_accept_encoding ~ gzip) {
	        set $rocket_encryption "_gzip";
        }
        
        # Is Brotli accepted by client ?
        if ($http_accept_encoding ~ br) {
	        set $rocket_encryption "";
        }
        
        # Is HTTPS request ?
        if ($https = "on") { set $rocket_is_https 1; }
        if ($http_x_forwarded_proto = "https") { set $rocket_is_https 1; }
        if ($http_front_end_https = "on") { set $rocket_is_https 1; }
        if ($http_x_forwarded_protocol = "https") { set $rocket_is_https 1; }
        if ($http_x_forwarded_ssl = "on") { set $rocket_is_https 1; }
        if ($http_x_url_scheme = "https") { set $rocket_is_https 1; }
        if ($http_forwarded ~ /proto=https/) { set $rocket_is_https 1; }
        
        if ($rocket_is_https = "1") {
	        set $rocket_https_prefix "-https";
        }
        
        # Check if request supports WebP ?
        if ($http_accept ~* "webp") {
	        set $rocket_support_webp "1";
        }
        
        # Set mobile detection file path
        set $rocket_mobile_detection "$document_root/wp-content/cache/wp-rocket/$http_host/$request_uri/.mobile-active";
        
        # Query strings to ignore
        set $rocket_args $args;
        if ($rocket_args ~ (.*)(?:&|^)utm_source=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_campaign=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_medium=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_expid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_term=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_content=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_id=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_source_platform=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_creative_format=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)utm_marketing_tactic=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)_ga=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)gclid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)campaignid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)adgroupid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)adid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)gbraid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)wbraid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)gclsrc=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)ef_id=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)fb_action_ids=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)fb_action_types=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)fb_source=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)fbclid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mc_cid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mc_eid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_source=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_medium=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_campaign=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_keyword=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_cid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)mtm_content=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)_ke=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)age-verified=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)ao_noptimize=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)usqp=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)cn-reloaded=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)sscid=[^&]*(.*)) { set $rocket_args $1$2; }
        if ($rocket_args ~ (.*)(?:&|^)msclkid=[^&]*(.*)) { set $rocket_args $1$2; }
        
        # Remove & at the beginning (if needed)
        if ($rocket_args ~ ^&(.*)) { set $rocket_args $1;  }
        
        
        # Do not count arguments if part of caching arguments
        if ($rocket_args ~ ^\?$) {
	        set $rocket_is_args "";
        }
        
        
        if ($rocket_args = "") {
	        set $rocket_is_args "";
        }
        
        # Query string to cache
        
        
        # File/URL to return IF we must bypass WordPress
        # Desktop: index.html
        # Gzip:    index.html_gzip
        # HTTPS:   index-https.html
        # Mobile:  index-mobile-https.html
        
        set $rocket_file_start "index$rocket_https_prefix";
        
        set $rocket_pre_url "/wp-content/cache/wp-rocket/$http_host/$rocket_uri_path/$rocket_args/";
        set $rocket_pre_file "$document_root/wp-content/cache/wp-rocket/$http_host/$rocket_uri_path/$rocket_args/";
        
        # Standard cache file format
        set $rocket_url "$rocket_pre_url$rocket_file_start$rocket_dynamic.html";
        set $rocket_file "$rocket_pre_file$rocket_file_start$rocket_dynamic.html";
        
        # Check if gzip version cached file is available
        if (-f "$rocket_file$rocket_encryption") {
	        set $rocket_file "$rocket_file$rocket_encryption";
	        set $rocket_url  "$rocket_url$rocket_encryption";
        }
        
        # Do not bypass if the cached file does not exist
        if (!-f "$rocket_file") {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "MISS";
	        set $rocket_reason "File not cached";
        }
        
        # Do not bypass if it's a POST request
        if ($request_method = POST) {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "BYPASS";
	        set $rocket_reason "POST request";
        }
        
        # Do not bypass if arguments are found (e.g. ?page=2)
        if ($rocket_is_args) {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "BYPASS";
	        set $rocket_reason "Arguments found";
        }
        
        # Do not bypass if the site is in maintenance mode
        if (-f "$document_root/.maintenance") {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "BYPASS";
	        set $rocket_reason "Maintenance mode";
        }
        
        # Do not bypass if one of those cookie if found
        # wordpress_logged_in_[hash] : When a user is logged in, this cookie is created (we'd rather let WP-Rocket handle that)
        # wp-postpass_[hash] : When a protected post requires a password, this cookie is created.
        if ($http_cookie ~* "(wordpress_logged_in_|wp\-postpass_|woocommerce_items_in_cart|woocommerce_cart_hash|wptouch_switch_toogle|comment_author_|comment_author_email_)") {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "BYPASS";
	        set $rocket_reason "Cookie";
        }
        
        if (-f "$rocket_mobile_detection") {
	        set $rocket_bypass 0;
	        set $rocket_is_bypassed "BYPASS";
	        set $rocket_reason "Specific mobile cache activated";	
        }
        
        # If the bypass token is still on, let's bypass WordPress with the cached URL
        if ($rocket_bypass = 1) {
	        set $rocket_is_bypassed "HIT";
	        set $rocket_reason "$rocket_url";
        }
        
        # Clear variables if debug is not needed
        if ($rocket_debug = 0) {
	        set $rocket_reason "";
	        set $rocket_file "";
        }
        
        # If the bypass token is still on, rewrite according to the file linked to the request
        if ($rocket_bypass = 1) {
	        rewrite .* "$rocket_url" last;
        }
        
        # Add header to HTML cached files
        location ~ /wp-content/cache/wp-rocket/.*html$ {
	        etag on;
	        add_header Vary "Accept-Encoding, Cookie";
	        add_header Cache-Control "no-cache, no-store, must-revalidate";
	        add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
	        add_header X-Rocket-Nginx-Reason $rocket_reason;
	        add_header X-Rocket-Nginx-File $rocket_file;
	        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
	        include /etc/nginx/rocket-nginx/conf.d/default/http.*.conf;
        }
        
        # Do not gzip cached files that are already gzipped
        location ~ /wp-content/cache/wp-rocket/.*_gzip$ {
	        etag on;
	        gzip off;
	        types {}
	        default_type text/html;
	        add_header Content-Encoding gzip;
	        add_header Vary "Accept-Encoding, Cookie";
	        add_header Cache-Control "no-cache, no-store, must-revalidate";
	        add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
	        add_header X-Rocket-Nginx-Reason $rocket_reason;
	        add_header X-Rocket-Nginx-File $rocket_file;
	        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
	        include /etc/nginx/rocket-nginx/conf.d/default/http.*.conf;
        }
        
        # Debug header (when file is not cached)
        add_header X-Rocket-Nginx-Serving-Static $rocket_is_bypassed;
        add_header X-Rocket-Nginx-Reason $rocket_reason;
        add_header X-Rocket-Nginx-File $rocket_file;
        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
        
        
        ###################################################################################################
        # BROWSER CSS CACHE
        #
        location ~* \.css$ {
	        etag on;
	        gzip_vary on;
	        expires 30d;
	        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
	        include /etc/nginx/rocket-nginx/conf.d/default/css.*.conf;
        }
        
        
        ###################################################################################################
        # BROWSER JS CACHE
        #
        location ~* \.js$ {
	        etag on;
	        gzip_vary on;
	        expires 30d;
	        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
	        include /etc/nginx/rocket-nginx/conf.d/default/js.*.conf;
        }
        
        
        ###################################################################################################
        # BROWSER MEDIA CACHE
        #
        location ~* \.(ico|gif|jpe?g|png|svg|eot|otf|woff|woff2|ttf|ogg|webp)$ {
	        etag on;
	        expires 30d;
	        include /etc/nginx/rocket-nginx/conf.d/default/global.*.conf;
	        include /etc/nginx/rocket-nginx/conf.d/default/media.*.conf;
        }

**Expected behavior**
There probably should be a command telling NGiNX to actually use $rocket_support_webp somewhere in the default.conf file generated – as far as I understand, this is simply set to 1 but never actually used in the URL generation scheme?

**Additional context**
Note that the gzip version of the file similarily is never used.

**Comment by maximejobin** [comment]
This feature is not supported as it depends on the browser. Nginx's scripting language does not make it possible to verify all conditions easily.

On a personal note, I've never understood this feature. With the AVIF format on the rise, I have no plan to try to support this.

IMHO, you should really replace your current images with WEBP and not use the WEBP feature from WP Rocket. This is only my opinion.
