### ISSUE TITLE
LAMP/LEMP Stack Combo and Rocket-Nginx...

### ISSUE THREAD

**Issue by BradFD** [SatelliteWP/rocket-nginx#216]
Will rocket-nginx work if you use Nginx as a proxy in front of Apache like Serverpilot.io configures? 
https://serverpilot.io/docs/how-serverpilot-configures-your-lamp-stack/

Thank you.

**Comment by maximejobin** [comment]
> Will rocket-nginx work if you use Nginx as a proxy in front of Apache

That being said, I haven't used ServerPilot in years so I don't know how easy it is to include Rocket-Nginx in its configuration.
