### ISSUE TITLE
MISS if use HTTP3.0

### ISSUE THREAD

**Issue by PauloOF** [SatelliteWP/rocket-nginx#217]
Hi Maxime,

Do you know why I'm getting "x-rocket-nginx-serving-static: MISS" if use HTTP3.0 protocol? 
See bellow headers thawe have got with curl.

HTTP/3 200
server: nginx
date: Fri, 14 Jun 2024 18:06:17 GMT
content-type: text/html; charset=UTF-8
vary: accept-encoding
last-modified: Fri, 14 Jun 2024 18:00:02 GMT
alt-svc: h3=":443"; ma=86400
strict-transport-security: max-age=15768000; includeSubDomains
x-rocket-nginx-serving-static: MISS
x-content-type-options: nosniff
x-frame-options: sameorigin

HTTP/2 200
server: nginx
date: Fri, 14 Jun 2024 18:09:33 GMT
content-type: text/html
content-length: 341885
last-modified: Fri, 14 Jun 2024 18:00:02 GMT
vary: Accept-Encoding
etag: "666c8522-5377d"
alt-svc: h3=":443"; ma=86400
vary: Accept-Encoding, Cookie
cache-control: public, max-age=600
x-content-type-options: nosniff
x-frame-options: sameorigin
strict-transport-security: max-age=31536000
x-rocket-nginx-serving-static: HIT
accept-ranges: bytes

**Comment by maximejobin** [comment]
Please activate the debug and post the headers you see. This will help me help you!

**Comment by PauloOF** [comment]
Curl With HTTP3:

HTTP/3 200
server: nginx
date: Mon, 17 Jun 2024 16:20:17 GMT
content-type: text/html; charset=UTF-8
vary: accept-encoding
last-modified: Mon, 17 Jun 2024 16:00:02 GMT
alt-svc: h3=":443"; ma=86400
strict-transport-security: max-age=15768000; includeSubDomains
x-rocket-nginx-serving-static: MISS
x-rocket-nginx-reason: File not cached
x-rocket-nginx-file: /var/www/vhosts/domain.com/httpdocs/wp-content/cache/wp-rocket/////index-https.html
x-content-type-options: nosniff
x-frame-options: sameorigin

Curl with http2
HTTP/2 200
server: nginx
date: Mon, 17 Jun 2024 16:22:08 GMT
content-type: text/html
content-length: 339684
last-modified: Mon, 17 Jun 2024 16:00:02 GMT
vary: Accept-Encoding
etag: "66705d82-52ee4"
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
vary: Accept-Encoding, Cookie
cache-control: public, max-age=600
x-content-type-options: nosniff
x-frame-options: sameorigin
strict-transport-security: max-age=31536000
x-rocket-nginx-serving-static: HIT
x-rocket-nginx-reason: /wp-content/cache/wp-rocket/domain.com////index-https.html
x-rocket-nginx-file: /var/www/vhosts/domain.com/httpdocs/wp-content/cache/wp-rocket/domain.com////index-https.html
accept-ranges: bytes

**Comment by maximejobin** [comment]
It seems like there was a missing variable in your Nginx/Fast CGI configuration.

Instead of replacing `$http_host` manually, you should edit your Fast CGI param to bind the host to the variable. That way, the script will work properly.

By not doing this, you surely WILL have issues with other scripts (WordPress itself, plugins, etc.) at some point.

I will close the issue as this is related to your Nginx & Fast CGI configuration. If you find the solution, it would be nice if you comment below with your findings!

I wish you the best!

**Comment by PauloOF** [comment]
Thanks!

I'm using fastcgi_param HTTP_HOST $host; at  fastcgi.conf and seems its necessary to replace all usages of [$http_host] with [$host] in nginx config files. 

After a full server check, I have confirmed that only rocket-nginx uses [$http_host] instead of $host.

I think that this its the solution to make compatibility of the h3 protocol.

**Comment by maximejobin** [comment]
That is weird as we did not invent that variable!

If it's working for HTTP2, clearly your HTTP2 is configured to use it. You might want to check.
