### ISSUE TITLE
Issue with anti-bot solution Datadome

### ISSUE THREAD

**Issue by LaurentLeLynx** [SatelliteWP/rocket-nginx#218]
**Describe the bug**
For security we use a anti bot solution named Datadome. It seems Datadome doesn't work anymore when pages are server cached and display as 304 via rocket-nginx. 
We think that datadome nginx module is bypassed when the request goes through rocket-nginx. 
How to avoid that ? is it possible to add datadome config file in rocket-nginx ?

Thank you for your help.

**Versions**
What version of Nginx are you using ? --> nginx/1.18.0
What version of Rocket-Nginx are you using ? 3.0.0
What version of WP Rocket are you using ? 3.15.10

**Expected behavior**
Traffic must go through the Datadome solution.

**Comment by maximejobin** [comment]
I'm sorry but I do not use datadome and don't if/how it interacts with Nginx.

This is something you'll have to look on your own, unfortunately.
