### ISSUE TITLE
Add extended log status for NGINX Amplify

### ISSUE THREAD

**Issue by gshulegaard** [SatelliteWP/rocket-nginx#71]
Just moving discussion about this from:

https://github.com/maximejobin/rocket-nginx/issues/65

NGINX Amplify collects metrics based on your `access_log` format.  As an easy proposed change, I might suggest adding an extended log format to the generated rocket config:

```
log_format rocket '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for" ' '"$host" sn="$server_name" ' 'rt=$request_time ' 'ua="$upstream_addr" us="$upstream_status" ' 'ut="$upstream_response_time" ul="$upstream_response_length" ' 'cs=$upstream_cache_status' ;
```

And then using it like so:

```
access_log  /var/log/nginx/rocket.log  rocket;
```

For completeness, you might consider also enabling additional error logging:

```
error_log /var/log/nginx/error.log warn;
```

These are just the recommended defaults for enabling additional metrics from our docs:

https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#additional-nginx-metrics

For performance reasons you might want to tune/limit the number of variables being logged.  For that I would consider identifying key performance metrics for rocket users from this list:

https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#nginx-metrics

And changing the above settings appropriately.  It may be easier to let me know which metrics you are interested in and I can suggest a log format and error log level.

**Comment by maximejobin** [comment]
Well, I'm interested in a default configuration that would suit most people. Then, I would make it easy for people to alter it if they need to.

What do you think ?

**Comment by gshulegaard** [comment]
Sounds great!  I think the recommended config above should suit most use cases.

**Comment by maximejobin** [comment]
I'm revisiting this issue. Why does it have to be included in Rocket-Nginx?

Shouldn't be configured at a higher level?

**Comment by gshulegaard** [comment]
It's been awhile, but looking back over #65 I don't think it has to be included in rocket-nginx.  So long as a user can configure the log format (and enable error logging) the NGINX Amplify agent should be able to collect all required metrics.

You had expressed in interest in including a "default" log format that would work for most users, which is why I shared the Amplify recommended format and log settings.

Quite a bit has changed, and I am no longer working at NGINX or associated with the NGINX Amplify product/project directly, although I am happy to lend my (dated) knowledge to helping figure out what (if anything) to do here.

**Comment by maximejobin** [comment]
Thank you for you quick answer, Grant!

I do believe I misunderstood what Amplify would do and including it made no sense when I revisited. Thanks for the clarification. I will close that issue.
