### ISSUE TITLE
Rocket NGINX not working with Query Cache

### ISSUE THREAD

**Issue by five-team** [SatelliteWP/rocket-nginx#72]
There's one thin I can't get working your configuration with:

If I activate "Query Cache" in WP Rocket, the HTML File is served by Apache instead of NGINX.
Any idea whats the problem?

I mean this setting in WP Rocket:
http://docs.wp-rocket.me/article/971-caching-query-strings

The sites are cached by WP Rocket (HTML file is being generated), but instead of NGINX the Apache Webserver delivers them.

For example URLs like https://www.domain.com/article/?v=7236236

**Comment by maximejobin** [comment]
For now, the way Rocket-Nginx works is that if there is a query string, we don't serve a cache file. R&D could be done to see if there is a way for Rocket-Nginx to serve a cached file .

**Comment by five-team** [comment]
Any idea when this will be implemented in rocket nginx? :-)

**Comment by maximejobin** [comment]
I don't have a specific timeframe. I must check if that is possible. Then, if it is, I will implement it.

**Comment by goaround** [comment]
This could be even better than query cache, if you know your parameters and don't want to show a different page than without: https://github.com/maximejobin/rocket-nginx/pull/76

**Comment by kevin25** [comment]
@maximejobin Is there any way to compress the static files either?

**Comment by maximejobin** [comment]
@kevin25 https://github.com/maximejobin/rocket-nginx/issues/90#issuecomment-436382692

**Comment by maximejobin** [comment]
Now available in version 3.0.
