### ISSUE TITLE
Not adding trailing slash

### ISSUE THREAD

**Issue by jcatello** [SatelliteWP/rocket-nginx#88]
When using wp-rocket with the nginx config the trailing slashes are not added to the URL's when the cache is primed. Clear cache, trailing slashed is added, cache primed, no trailing slash

**Comment by maximejobin** [comment]
> the trailing slashes are not added to the URL's when the cache is primed

They are not added where ? Rocket-Nginx simply reads the files directly when the cache is generated. I'm not sure I get what you are describing so I can't investigate.

Please clarify.

**Comment by jcatello** [comment]
By default, WordPress adds trailing slashes to posts/pages.

When using wp-rocket, you can visit a post without a trailing slash

domain.com/post-name

and it does not redirect to

domain.com/post-name/

if I clear wp-rocket cache, the next time I refresh that page it will then redirect with the trailing slash, however since that refresh primes the cache for that page, if I visit that page again with no trailing slash, it does not redirect with the trailing slash.

For now we've added a redirect in the nginx conf to add trailing slash to URL's but shouldn't have to since that functionality is built into WP, it helps Google to not penalize for duplicate content since it treats the URL as 2 seperate URL's which gives us duplicate content.

I'm assuming since the goal of wp-rocket is to bypass PHP and serve the cache directly, its not allowing the functionality of WordPress which relies on PHP to do the redirect.

**Comment by jcatello** [comment]
To add, we use a few different caching plugins, but wp-rocket seems to be the only one with this issue that I've seen.

**Comment by jcatello** [comment]
Sure as a quick fix we've been using:

[https://stackoverflow.com/a/3912675/2364144](url)

**Comment by maximejobin** [comment]
I was doing some testing and it is true the / is not added.

That being said, it won't have any impact on your SEO because the canonical tag includes it. You won't be penalized for that.

**Comment by Dibbyo456** [comment]
@jcatello I'm having the exact same issue, gonna rely on redirect for now until @maximejobin sort this out.

**Comment by maximejobin** [comment]
@Dibbyo456 What problem are you trying to solve exactly ?

Why is not having a trailing slash an issue ?

**Comment by Dibbyo456** [comment]
The exact same problem OP was having.

Trailing slash not added when cache is served.

**Comment by maximejobin** [comment]
I know it's not added. The question is: **Why is not having a trailing slash an issue ?**

**Comment by Dibbyo456** [comment]
I was gonna say SEO. But you already said this:

> That being said, it won't have any impact on your SEO because the canonical tag includes it. You won't be penalized for that.

My question is where is it added?

**Comment by maximejobin** [comment]
If you have a SEO plugin like [Yoast SEO](https://en-ca.wordpress.org/plugins/wordpress-seo/) (for instance), the canonical reference is added automatically.

Source from my personal website with a trailing slash in the URL:
![image](https://user-images.githubusercontent.com/1080760/51348563-0b9d5e00-1a71-11e9-9c72-c2bc1d0997f3.png)


Source from my personal website without a trailing slash in the URL :

![image](https://user-images.githubusercontent.com/1080760/51348446-c842ef80-1a70-11e9-9b55-79e10058919c.png)

Therefore, having a trailing slash (or not) has no impact on SEO and is not a problem at all.

**Comment by Dibbyo456** [comment]
Aah. I do use Yoast. Thank you for explaining..

**Comment by jcatello** [comment]
@maximejobin Sorry to bring this back but having more and more issues where GA is now reporting on both URL's with and without trailing slash even when the canonical URL is set, example:

![image](https://user-images.githubusercontent.com/3605615/57585448-427f0000-74b6-11e9-9166-6299a96922be.png)

**Comment by maximejobin** [comment]
The easy answer would be: Why don't you fix your URLs on your website ?

There is complexity to your request as you don't want to add a slash to everything:

/css/styles.css
/products?page=2
...

We would need all possibilities to evaluate what must be done. I'm reopening the ticket and asking your help for that.

Can you think of more use cases?

**Comment by blogtutor** [comment]
I'm going to jump in here since we have clients reporting this issue as well.

> Why don't you fix your URLs on your website ?

I assume you mean that people should make sure to always including the trailing slash when adding internal links to their sites. However, many clients don't understand the difference, and since the link appears to work.  So they may not notice this nuanced difference.

> Therefore, having a trailing slash (or not) has no impact on SEO and is not a problem at all.

This was my position as well (as long as the canonical tags were correctly set with the trailing slash), until recently I talked with one SEO export who pointed out that:
1. Canonical tags are only a suggestion/hint to google, and,
2. Links can be a stronger hint than Canonical tags (especially if there are many, such as an internal link on every page of a site, in the sidebar or some such), and,
3. Once Google decides the links are more important for a specific page, it may decide to discount the Canonical tags sitewide.

@jcatello also raised the excellent point about the Google Analytics reports showing two URLs, making reporting more complicated.

So at this point, I think the best practice would be to continue to redirect to add the trailing slash (as WordPress does by default), in order to avoid any of these issues.

**Comment by blogtutor** [comment]
Also, WP Rocket has documentation for adding this back in for .htaccess

https://docs.wp-rocket.me/article/131-redirection-to-enforce-trailing-slash-on-urls

**Comment by kirillrocks** [comment]
Same issue here, alot of clients reporting it, and the answer of "there is a canonical" is just not enough. It is a problem needs attending. 

Without wprocket cache, the automatic WP redirect works perfectly.

**Comment by maximejobin** [comment]
> alot of clients reporting it

What do you mean by that @kirillrocks?

**Comment by maximejobin** [comment]
The rule could be added in your own configuration extension file that you can now include with version 3.0.

Closing this.
